{
  "hash": "f4873d1c7273ad91ec2b380f470182c5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Study C: Grid Resolution\"\nsubtitle: \"Registration Benchmark v2\"\n---\n\n# Setup {.unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(data.table)\nlibrary(patchwork)\n\nbase_dir <- here::here()\nsource(file.path(base_dir, \"sim-analyze.R\"))\n\nmcols <- method_colors()\nmlabs <- method_labels()\ndlabs <- dgp_short_labels()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndt <- load_study_c()\n```\n:::\n\n\nStudy C tests whether **grid resolution** is a confound for method comparison.\nSRVF operates on SRSFs (numerical derivatives) which amplify discretization artifacts\nat finer grids. A preliminary pilot (job 5131384) showed SRVF warp MISE 1.82× worse at\n$n_\\text{grid}=201$ vs 101.\n\n**Design**: 5 DGPs $\\times$ 3 grid sizes (51, 101, 201) $\\times$ 3 noise (0, 0.1, 0.3)\n$\\times$ 5 methods $\\times$ severity=1.0 = 225 cells $\\times$ 50 reps = 11,250 runs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndgps_used <- c(\"D01\", \"D03\", \"D04\", \"D09\", \"D12\")\nknitr::kable(\n  dgp_factors()[dgp %in% dgps_used],\n  caption = \"DGPs in Study C: covering both templates, all 3 warp types, and none/highrank amplitude.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: DGPs in Study C: covering both templates, all 3 warp types, and none/highrank amplitude.\n\n|dgp |template |warp_type |amplitude |\n|:---|:--------|:---------|:---------|\n|D01 |harmonic |simple    |none      |\n|D03 |wiggly   |complex   |none      |\n|D04 |harmonic |affine    |none      |\n|D09 |harmonic |simple    |highrank  |\n|D12 |wiggly   |complex   |highrank  |\n\n\n:::\n:::\n\n\n# Overview {#sec-overview}\n\n## Failure Rates\n\n\n```{.r .cell-code}\nfail_dt <- dt[,\n  .(n_fail = sum(failure), n_total = .N, rate = mean(failure)),\n  by = .(method, n_grid)\n]\nfail_any <- fail_dt[n_fail > 0]\nif (nrow(fail_any) == 0) {\n  cat(\"No failures across all 11,250 runs.\\n\\n\")\n} else {\n  cat(\"**Failure rates by method and grid:**\\n\\n\")\n  print(knitr::kable(fail_dt[n_fail > 0]))\n}\n```\n\n**Failure rates by method and grid:**\n\n\n\n|method        |n_grid | n_fail| n_total|  rate|\n|:-------------|:------|------:|-------:|-----:|\n|landmark_auto |51     |      3|     750| 0.004|\n|landmark_auto |101    |      6|     750| 0.008|\n|landmark_auto |201    |      1|     750| 0.001|\n\n## Warp MISE by Grid $\\times$ Method\n\nThe central question: does grid resolution systematically affect method performance?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = warp_mise, fill = n_grid)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2, position = \"dodge\") +\n  facet_wrap(~noise_sd, labeller = labeller(noise_sd = function(x) paste0(\"noise=\", x))) +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  scale_fill_brewer(palette = \"Set2\", name = \"Grid size\") +\n  labs(y = NULL, x = \"Warp MISE (log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Warp MISE by grid size and method, faceted by noise level. Each boxplot pools over all 5 DGPs and 50 reps.](sim-report-grid_files/figure-html/warp-mise-grid-method-1.png){width=960}\n:::\n:::\n\n\n# Grid Degradation Ratios {#sec-ratios}\n\nGrid degradation ratios compare each grid size to the baseline $n_\\text{grid}=101$.\nValues > 1 mean worse performance at that grid; < 1 means better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nratio_rep <- dcast(\n  dt[failure == FALSE, .(dgp, method, noise_sd, rep, n_grid, warp_mise)],\n  dgp + method + noise_sd + rep ~ n_grid,\n  value.var = \"warp_mise\"\n)\nratio_rep[, ratio_51 := `51` / `101`]\nratio_rep[, ratio_201 := `201` / `101`]\nratio_rep <- melt(\n  ratio_rep,\n  id.vars = c(\"dgp\", \"method\", \"noise_sd\", \"rep\"),\n  measure.vars = c(\"ratio_51\", \"ratio_201\"),\n  variable.name = \"n_grid\",\n  value.name = \"ratio\"\n)\nratio_rep[, n_grid := sub(\"^ratio_\", \"\", n_grid)]\nratio_dt <- ratio_rep[, .(\n  ratio = median(ratio, na.rm = TRUE),\n  q25 = quantile(ratio, 0.25, na.rm = TRUE),\n  q75 = quantile(ratio, 0.75, na.rm = TRUE)\n), by = .(dgp, method, n_grid, noise_sd)]\n\nggplot(ratio_dt, aes(x = ratio, y = method, color = method)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n  geom_point(size = 2, alpha = 0.7) +\n  geom_errorbarh(aes(xmin = q25, xmax = q75), height = 0.15, alpha = 0.3) +\n  geom_text(aes(label = dgp), size = 3, vjust = -0.8, show.legend = FALSE) +\n  stat_summary(fun = median, geom = \"crossbar\", width = 0.4,\n    color = \"black\", linewidth = 0.4) +\n  facet_grid(n_grid ~ noise_sd,\n    labeller = labeller(\n      noise_sd = function(x) paste0(\"noise=\", x),\n      n_grid = function(x) paste0(\"grid=\", x)\n    )\n  ) +\n  scale_color_manual(values = mcols, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_continuous(trans = \"log2\",\n    breaks = c(0.25, 0.5, 1, 2, 4),\n    labels = c(\"1/4\", \"1/2\", \"1\", \"2\", \"4\")\n  ) +\n  labs(x = expression(\"Warp MISE ratio vs grid=101 (\" * log[2] * \" scale)\"), y = NULL) +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Warp MISE ratio relative to grid=101, per method and noise level. Each labeled point is one DGP; horizontal bars show the IQR of paired per-rep ratios and the crossbar shows the median across DGPs. Values > 1 (right of dashed line) indicate degradation.](sim-report-grid_files/figure-html/grid-ratios-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Median ratio per method x grid x noise\nratio_by_noise <- ratio_dt[,\n  .(median_ratio = median(ratio, na.rm = TRUE)),\n  by = .(method, n_grid, noise_sd)\n]\nratio_uncertainty <- mean_se_table(ratio_dt, \"ratio\", c(\"method\", \"n_grid\", \"noise_sd\"))\n\n# SRVF noise-dependent reversal (the key finding)\nsrvf_rats <- ratio_by_noise[method == \"srvf\"]\nsrvf_unc <- ratio_uncertainty[method == \"srvf\"]\ncat(\"**Key finding: SRVF grid sensitivity reverses with noise level.**\\n\\n\")\n```\n\n**Key finding: SRVF grid sensitivity reverses with noise level.**\n\n```{.r .cell-code}\ntbl_lines <- c(\n  \"SRVF warp MISE ratios (vs grid=101):\\n\",\n  \"| Noise | grid=51 | grid=201 |\",\n  \"|-------|---------|----------|\"\n)\nfor (ns in c(\"0\", \"0.1\", \"0.3\")) {\n  r51 <- srvf_rats[n_grid == \"51\" & noise_sd == ns, median_ratio]\n  r201 <- srvf_rats[n_grid == \"201\" & noise_sd == ns, median_ratio]\n  se51 <- srvf_unc[n_grid == \"51\" & noise_sd == ns, se]\n  se201 <- srvf_unc[n_grid == \"201\" & noise_sd == ns, se]\n  tbl_lines <- c(tbl_lines, sprintf(\n    \"| %s | %.2f ± %.2f | %.2f ± %.2f |\",\n    ns, r51, se51, r201, se201\n  ))\n}\ncat(paste(tbl_lines, collapse = \"\\n\"), \"\\n\\n\")\n```\n\nSRVF warp MISE ratios (vs grid=101):\n\n| Noise | grid=51 | grid=201 |\n|-------|---------|----------|\n| 0 | 2.26 ± 0.87 | 0.91 ± 0.19 |\n| 0.1 | 0.93 ± 0.21 | 1.73 ± 0.92 |\n| 0.3 | 0.73 ± 0.02 | 1.20 ± 0.19 | \n\n```{.r .cell-code}\ncat(\"At noise=0, coarser grid *hurts* SRVF — DP alignment on 51 points is too \",\n  \"imprecise to resolve the warp. At noise>0, finer grid *hurts* SRVF — \",\n  \"numerical differentiation amplifies noise at 201 points, acting as \",\n  \"de facto anti-regularization.\\n\\n\")\n```\n\nAt noise=0, coarser grid *hurts* SRVF — DP alignment on 51 points is too  imprecise to resolve the warp. At noise>0, finer grid *hurts* SRVF —  numerical differentiation amplifies noise at 201 points, acting as  de facto anti-regularization.\n\n```{.r .cell-code}\n# All methods summary\ncat(\"**All methods** (median ratio, pooled over DGPs and noise — \",\n  \"descriptive only; SRVF pooled medians mask the noise-dependent reversal above):\\n\\n\")\n```\n\n**All methods** (median ratio, pooled over DGPs and noise —  descriptive only; SRVF pooled medians mask the noise-dependent reversal above):\n\n```{.r .cell-code}\nratio_summary <- ratio_dt[,\n  .(\n    median_ratio = median(ratio, na.rm = TRUE),\n    mean_ratio = mean(ratio, na.rm = TRUE),\n    se_ratio = if (.N > 1) sd(ratio, na.rm = TRUE) / sqrt(.N) else 0,\n    min_ratio = min(ratio, na.rm = TRUE),\n    max_ratio = max(ratio, na.rm = TRUE)\n  ),\n  by = .(method, n_grid)\n]\nfor (g in sort(unique(as.character(ratio_summary$n_grid)))) {\n  cat(sprintf(\"*Grid = %s:*\\n\\n\", g))\n  sub <- ratio_summary[n_grid == g][order(median_ratio)]\n  for (i in seq_len(nrow(sub))) {\n    cat(sprintf(\"- **%s**: median %.2f; mean %.2f ± %.2f; range [%.2f, %.2f]\\n\",\n      mlabs[sub$method[i]], sub$median_ratio[i],\n      sub$mean_ratio[i], sub$se_ratio[i],\n      sub$min_ratio[i], sub$max_ratio[i]))\n  }\n  cat(\"\\n\")\n}\n```\n\n*Grid = 201:*\n\n- **FDA (default)**: median 0.97; mean 0.96 ± 0.05; range [0.62, 1.29]\n- **FDA (crit 1)**: median 0.99; mean 0.98 ± 0.03; range [0.68, 1.19]\n- **Landmark (auto)**: median 1.01; mean 1.01 ± 0.01; range [0.87, 1.07]\n- **Affine (S+S)**: median 1.02; mean 1.03 ± 0.03; range [0.85, 1.27]\n- **SRVF**: median 1.24; mean 1.71 ± 0.39; range [0.17, 6.39]\n\n*Grid = 51:*\n\n- **SRVF**: median 0.93; mean 1.46 ± 0.38; range [0.30, 5.33]\n- **Affine (S+S)**: median 0.99; mean 0.99 ± 0.05; range [0.73, 1.41]\n- **Landmark (auto)**: median 1.00; mean 1.04 ± 0.03; range [0.84, 1.37]\n- **FDA (default)**: median 1.04; mean 1.01 ± 0.04; range [0.64, 1.26]\n- **FDA (crit 1)**: median 1.06; mean 1.07 ± 0.05; range [0.80, 1.43]\n\n# Template MISE by Grid {#sec-template}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = template_mise, fill = n_grid)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2, position = \"dodge\") +\n  facet_wrap(~noise_sd, labeller = labeller(noise_sd = function(x) paste0(\"noise=\", x))) +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  scale_fill_brewer(palette = \"Set2\", name = \"Grid size\") +\n  labs(y = NULL, x = \"Template MISE (log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Template MISE by grid size and method, faceted by noise level.](sim-report-grid_files/figure-html/template-mise-grid-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_ratio_rep <- dcast(\n  dt[failure == FALSE, .(dgp, method, noise_sd, rep, n_grid, template_mise)],\n  dgp + method + noise_sd + rep ~ n_grid,\n  value.var = \"template_mise\"\n)\nt_ratio_rep[, ratio_51 := `51` / `101`]\nt_ratio_rep[, ratio_201 := `201` / `101`]\nt_ratio_rep <- melt(\n  t_ratio_rep,\n  id.vars = c(\"dgp\", \"method\", \"noise_sd\", \"rep\"),\n  measure.vars = c(\"ratio_51\", \"ratio_201\"),\n  variable.name = \"n_grid\",\n  value.name = \"ratio\"\n)\nt_ratio_rep[, n_grid := sub(\"^ratio_\", \"\", n_grid)]\nt_ratio_dt <- t_ratio_rep[, .(\n  ratio = median(ratio, na.rm = TRUE),\n  q25 = quantile(ratio, 0.25, na.rm = TRUE),\n  q75 = quantile(ratio, 0.75, na.rm = TRUE)\n), by = .(dgp, method, n_grid, noise_sd)]\n\nggplot(t_ratio_dt, aes(x = ratio, y = method, color = method)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n  geom_point(size = 2, alpha = 0.7) +\n  geom_errorbarh(aes(xmin = q25, xmax = q75), height = 0.15, alpha = 0.3) +\n  geom_text(aes(label = dgp), size = 3, vjust = -0.8, show.legend = FALSE) +\n  stat_summary(fun = median, geom = \"crossbar\", width = 0.4,\n    color = \"black\", linewidth = 0.4) +\n  facet_grid(n_grid ~ noise_sd,\n    labeller = labeller(\n      noise_sd = function(x) paste0(\"noise=\", x),\n      n_grid = function(x) paste0(\"grid=\", x)\n    )\n  ) +\n  scale_color_manual(values = mcols, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_continuous(trans = \"log2\",\n    breaks = c(0.25, 0.5, 1, 2, 4),\n    labels = c(\"1/4\", \"1/2\", \"1\", \"2\", \"4\")\n  ) +\n  labs(x = expression(\"Template MISE ratio vs grid=101 (\" * log[2] * \" scale)\"), y = NULL) +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Template MISE ratio relative to grid=101. Each labeled point is one DGP and horizontal bars show the IQR of paired per-rep ratios. Values < 1 mean that grid improves template estimation.](sim-report-grid_files/figure-html/template-ratio-1.png){width=960}\n:::\n:::\n\n\n# Elastic Distance by Grid {#sec-elastic}\n\nSRSF elastic distance is reparameterization-invariant. A numerical convergence test\nshows that finer grids yield slightly larger elastic distances for fixed function pairs\n(~4% from grid=51 to 1001 for smooth functions), but this effect is far too small to\nexplain the patterns below. The large grid effects visible under noise are genuine:\nfiner grids provide more noisy observation points to the template estimator, degrading\nthe estimated template shape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (\"template_elastic_dist\" %in% names(dt) && any(!is.na(dt$template_elastic_dist))) {\n  ggplot(\n    dt[failure == FALSE & !is.na(template_elastic_dist)],\n    aes(y = method, x = template_elastic_dist, fill = n_grid)\n  ) +\n    geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2, position = \"dodge\") +\n    facet_wrap(~noise_sd,\n      labeller = labeller(noise_sd = function(x) paste0(\"noise=\", x))) +\n    scale_y_discrete(labels = mlabs) +\n    scale_x_log10() +\n    scale_fill_brewer(palette = \"Set2\", name = \"Grid size\") +\n    labs(y = NULL, x = \"Elastic distance (log scale)\") +\n    theme_benchmark()\n} else {\n  cat(\"*Elastic distance not available in results.*\")\n}\n```\n\n::: {.cell-output-display}\n![Elastic (SRSF) template distance by grid size and method.](sim-report-grid_files/figure-html/elastic-grid-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (\"template_elastic_dist\" %in% names(dt) && any(!is.na(dt$template_elastic_dist))) {\n  e_ratio_rep <- dcast(\n    dt[failure == FALSE & !is.na(template_elastic_dist),\n      .(dgp, method, noise_sd, rep, n_grid, template_elastic_dist)],\n    dgp + method + noise_sd + rep ~ n_grid,\n    value.var = \"template_elastic_dist\"\n  )\n  e_ratio_rep[, ratio_51 := `51` / `101`]\n  e_ratio_rep[, ratio_201 := `201` / `101`]\n  e_ratio_rep <- melt(\n    e_ratio_rep,\n    id.vars = c(\"dgp\", \"method\", \"noise_sd\", \"rep\"),\n    measure.vars = c(\"ratio_51\", \"ratio_201\"),\n    variable.name = \"n_grid\",\n    value.name = \"ratio\"\n  )\n  e_ratio_rep[, n_grid := sub(\"^ratio_\", \"\", n_grid)]\n  e_ratio_dt <- e_ratio_rep[, .(\n    ratio = median(ratio, na.rm = TRUE),\n    q25 = quantile(ratio, 0.25, na.rm = TRUE),\n    q75 = quantile(ratio, 0.75, na.rm = TRUE)\n  ), by = .(dgp, method, n_grid, noise_sd)]\n\n  print(\n    ggplot(e_ratio_dt, aes(x = ratio, y = method, color = method)) +\n      geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n      geom_point(size = 2, alpha = 0.7) +\n      geom_errorbarh(aes(xmin = q25, xmax = q75), height = 0.15, alpha = 0.3) +\n      geom_text(aes(label = dgp), size = 3, vjust = -0.8, show.legend = FALSE) +\n      stat_summary(fun = median, geom = \"crossbar\", width = 0.4,\n        color = \"black\", linewidth = 0.4) +\n      facet_grid(n_grid ~ noise_sd,\n        labeller = labeller(\n          noise_sd = function(x) paste0(\"noise=\", x),\n          n_grid = function(x) paste0(\"grid=\", x)\n        )\n      ) +\n      scale_color_manual(values = mcols, guide = \"none\") +\n      scale_y_discrete(labels = mlabs) +\n      scale_x_continuous(trans = \"log2\",\n        breaks = c(0.25, 0.5, 1, 2, 4),\n        labels = c(\"1/4\", \"1/2\", \"1\", \"2\", \"4\")\n      ) +\n      labs(\n        x = expression(\"Elastic distance ratio vs grid=101 (\" * log[2] * \" scale)\"),\n        y = NULL\n      ) +\n      theme_benchmark()\n  )\n}\n```\n\n::: {.cell-output-display}\n![Elastic distance ratio relative to grid=101. Each labeled point is one DGP and horizontal bars show the IQR of paired per-rep ratios. Values > 1 mean that grid degrades template shape recovery.](sim-report-grid_files/figure-html/elastic-ratio-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\nif (\"template_elastic_dist\" %in% names(dt) && any(!is.na(dt$template_elastic_dist))) {\n  e_ratio_dt2 <- dt[failure == FALSE & !is.na(template_elastic_dist),\n    .(elastic_dist = median(template_elastic_dist, na.rm = TRUE)),\n    by = .(dgp, method, n_grid, noise_sd)\n  ]\n  e_base2 <- e_ratio_dt2[n_grid == \"101\",\n    .(dgp, method, noise_sd, base = elastic_dist)]\n  e_ratio_dt2 <- merge(e_ratio_dt2, e_base2, by = c(\"dgp\", \"method\", \"noise_sd\"))\n  e_ratio_dt2[, ratio := elastic_dist / base]\n  e_ratio_dt2 <- e_ratio_dt2[n_grid != \"101\"]\n\n  e_summary <- e_ratio_dt2[,\n    .(median_ratio = median(ratio, na.rm = TRUE),\n      min_ratio = min(ratio, na.rm = TRUE),\n      max_ratio = max(ratio, na.rm = TRUE)),\n    by = .(method, n_grid)\n  ]\n\n  cat(\"**Elastic distance ratios vs grid=101** (median [min, max] across DGPs and noise):\\n\\n\")\n  for (g in sort(unique(as.character(e_summary$n_grid)))) {\n    cat(sprintf(\"*Grid = %s:*\\n\\n\", g))\n    sub <- e_summary[n_grid == g][order(median_ratio)]\n    for (i in seq_len(nrow(sub))) {\n      cat(sprintf(\"- **%s**: %.2f [%.2f, %.2f]\\n\",\n        mlabs[sub$method[i]], sub$median_ratio[i],\n        sub$min_ratio[i], sub$max_ratio[i]))\n    }\n    cat(\"\\n\")\n  }\n\n  # Check if elastic distance shows same SRVF pattern as warp MISE\n  srvf_e <- e_ratio_dt2[method == \"srvf\",\n    .(median_ratio = median(ratio, na.rm = TRUE)),\n    by = .(n_grid, noise_sd)\n  ]\n  srvf_e201_n0 <- srvf_e[n_grid == \"201\" & noise_sd == \"0\", median_ratio]\n  srvf_e201_n3 <- srvf_e[n_grid == \"201\" & noise_sd == \"0.3\", median_ratio]\n  if (length(srvf_e201_n0) > 0 && length(srvf_e201_n3) > 0) {\n    cat(sprintf(\n      \"SRVF elastic distance ratio at grid=201: %.2f (noise=0), %.2f (noise=0.3). \",\n      srvf_e201_n0, srvf_e201_n3\n    ))\n    if (srvf_e201_n3 > srvf_e201_n0) {\n      cat(\"Finer grids degrade template shape recovery more under noise, \",\n        \"consistent with the warp MISE pattern.\\n\")\n    } else {\n      cat(\"The pattern differs from warp MISE — elastic distance is less \",\n        \"sensitive to the grid × noise interaction for template estimation.\\n\")\n    }\n  }\n}\n```\n\n**Elastic distance ratios vs grid=101** (median [min, max] across DGPs and noise):\n\n*Grid = 201:*\n\n- **Affine (S+S)**: 1.08 [0.85, 1.88]\n- **FDA (crit 1)**: 1.10 [0.70, 2.02]\n- **Landmark (auto)**: 1.16 [0.95, 1.84]\n- **FDA (default)**: 1.19 [0.94, 2.17]\n- **SRVF**: 1.50 [0.48, 2.50]\n\n*Grid = 51:*\n\n- **SRVF**: 0.83 [0.46, 2.03]\n- **Affine (S+S)**: 0.99 [0.54, 1.16]\n- **FDA (crit 1)**: 1.04 [0.52, 1.75]\n- **FDA (default)**: 1.05 [0.53, 1.37]\n- **Landmark (auto)**: 1.12 [0.87, 1.32]\n\nSRVF elastic distance ratio at grid=201: 0.75 (noise=0), 1.53 (noise=0.3). Finer grids degrade template shape recovery more under noise,  consistent with the warp MISE pattern.\n\n# Alignment Error by Grid {#sec-alignment-error}\n\nAlignment error measures the practical downstream impact:\n$\\text{mean}_i \\int (\\hat{x}_i^{\\text{aligned}} - \\tilde{x}_i)^2\\,dt$.\nDo grid artifacts in warp estimation translate into worse alignment?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = alignment_error, fill = n_grid)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2, position = \"dodge\") +\n  facet_wrap(~noise_sd, labeller = labeller(noise_sd = function(x) paste0(\"noise=\", x))) +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  scale_fill_brewer(palette = \"Set2\", name = \"Grid size\") +\n  labs(y = NULL, x = \"Alignment error (log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Alignment error by grid size and method, faceted by noise level.](sim-report-grid_files/figure-html/ae-grid-method-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nae_ratio_rep <- dcast(\n  dt[failure == FALSE, .(dgp, method, noise_sd, rep, n_grid, alignment_error)],\n  dgp + method + noise_sd + rep ~ n_grid,\n  value.var = \"alignment_error\"\n)\nae_ratio_rep[, ratio_51 := `51` / `101`]\nae_ratio_rep[, ratio_201 := `201` / `101`]\nae_ratio_rep <- melt(\n  ae_ratio_rep,\n  id.vars = c(\"dgp\", \"method\", \"noise_sd\", \"rep\"),\n  measure.vars = c(\"ratio_51\", \"ratio_201\"),\n  variable.name = \"n_grid\",\n  value.name = \"ratio\"\n)\nae_ratio_rep[, n_grid := sub(\"^ratio_\", \"\", n_grid)]\nae_ratio_dt <- ae_ratio_rep[, .(\n  ratio = median(ratio, na.rm = TRUE),\n  q25 = quantile(ratio, 0.25, na.rm = TRUE),\n  q75 = quantile(ratio, 0.75, na.rm = TRUE)\n), by = .(dgp, method, n_grid, noise_sd)]\n\nggplot(ae_ratio_dt, aes(x = ratio, y = method, color = method)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n  geom_point(size = 2, alpha = 0.7) +\n  geom_errorbarh(aes(xmin = q25, xmax = q75), height = 0.15, alpha = 0.3) +\n  geom_text(aes(label = dgp), size = 3, vjust = -0.8, show.legend = FALSE) +\n  stat_summary(fun = median, geom = \"crossbar\", width = 0.4,\n    color = \"black\", linewidth = 0.4) +\n  facet_grid(n_grid ~ noise_sd,\n    labeller = labeller(\n      noise_sd = function(x) paste0(\"noise=\", x),\n      n_grid = function(x) paste0(\"grid=\", x)\n    )\n  ) +\n  scale_color_manual(values = mcols, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_continuous(trans = \"log2\",\n    breaks = c(0.25, 0.5, 1, 2, 4),\n    labels = c(\"1/4\", \"1/2\", \"1\", \"2\", \"4\")\n  ) +\n  labs(x = expression(\"Alignment error ratio vs grid=101 (\" * log[2] * \" scale)\"),\n    y = NULL) +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Alignment error ratio relative to grid=101, per method and noise level. Each labeled point is one DGP; horizontal bars show the IQR of paired per-rep ratios and the crossbar shows the median across DGPs.](sim-report-grid_files/figure-html/ae-grid-ratios-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\nae_ratio_summary <- ae_ratio_dt[,\n  .(median_ratio = median(ratio, na.rm = TRUE),\n    min_ratio = min(ratio, na.rm = TRUE),\n    max_ratio = max(ratio, na.rm = TRUE)),\n  by = .(method, n_grid)\n]\n\ncat(\"**Alignment error ratios vs grid=101** (median [min, max] across DGPs and noise):\\n\\n\")\n```\n\n**Alignment error ratios vs grid=101** (median [min, max] across DGPs and noise):\n\n```{.r .cell-code}\nfor (g in sort(unique(as.character(ae_ratio_summary$n_grid)))) {\n  cat(sprintf(\"*Grid = %s:*\\n\\n\", g))\n  sub <- ae_ratio_summary[n_grid == g][order(median_ratio)]\n  for (i in seq_len(nrow(sub))) {\n    cat(sprintf(\"- **%s**: %.2f [%.2f, %.2f]\\n\",\n      mlabs[sub$method[i]], sub$median_ratio[i],\n      sub$min_ratio[i], sub$max_ratio[i]))\n  }\n  cat(\"\\n\")\n}\n```\n\n*Grid = 201:*\n\n- **FDA (default)**: 1.00 [0.93, 1.12]\n- **Affine (S+S)**: 1.01 [0.84, 1.23]\n- **Landmark (auto)**: 1.04 [0.93, 1.10]\n- **FDA (crit 1)**: 1.04 [0.92, 1.15]\n- **SRVF**: 1.27 [0.51, 6.20]\n\n*Grid = 51:*\n\n- **SRVF**: 0.79 [0.35, 2.32]\n- **Affine (S+S)**: 0.91 [0.55, 1.34]\n- **Landmark (auto)**: 0.96 [0.83, 1.24]\n- **FDA (default)**: 0.97 [0.92, 1.37]\n- **FDA (crit 1)**: 1.00 [0.86, 1.19]\n\n```{.r .cell-code}\n# Compare with warp MISE ratios\nwarp_ratio_summary <- ratio_dt[,\n  .(warp_median = median(ratio, na.rm = TRUE)),\n  by = .(method, n_grid)\n]\nae_ratio_summary2 <- ae_ratio_dt[,\n  .(ae_median = median(ratio, na.rm = TRUE)),\n  by = .(method, n_grid)\n]\nboth <- merge(warp_ratio_summary, ae_ratio_summary2, by = c(\"method\", \"n_grid\"))\nr_grid <- cor(both$warp_median, both$ae_median, use = \"complete.obs\")\ncat(sprintf(\n  \"Correlation between warp MISE and alignment error grid ratios: r = %.2f. \",\n  r_grid))\n```\n\nCorrelation between warp MISE and alignment error grid ratios: r = 0.89. \n\n```{.r .cell-code}\nif (r_grid > 0.9) {\n  cat(\"Grid effects on warp recovery translate almost directly into alignment quality.\\n\\n\")\n} else {\n  cat(\"Grid effects on alignment error partially decouple from warp MISE — \",\n    \"alignment quality has some robustness to grid-induced warp artifacts.\\n\\n\")\n}\n```\n\nGrid effects on alignment error partially decouple from warp MISE —  alignment quality has some robustness to grid-induced warp artifacts.\n\n```{.r .cell-code}\n# SRVF-specific: does the noise-dependent reversal hold for alignment error too?\nsrvf_ae <- ae_ratio_dt[method == \"srvf\",\n  .(median_ratio = median(ratio, na.rm = TRUE)),\n  by = .(n_grid, noise_sd)]\nsrvf_ae51_n0 <- srvf_ae[n_grid == \"51\" & noise_sd == \"0\", median_ratio]\nsrvf_ae51_n3 <- srvf_ae[n_grid == \"51\" & noise_sd == \"0.3\", median_ratio]\nsrvf_ae201_n0 <- srvf_ae[n_grid == \"201\" & noise_sd == \"0\", median_ratio]\nsrvf_ae201_n3 <- srvf_ae[n_grid == \"201\" & noise_sd == \"0.3\", median_ratio]\n\nif (length(srvf_ae51_n0) > 0 && length(srvf_ae201_n3) > 0) {\n  cat(sprintf(\n    \"SRVF alignment error ratios: grid=51 is %.2f (noise=0), %.2f (noise=0.3); grid=201 is %.2f (noise=0), %.2f (noise=0.3). \",\n    srvf_ae51_n0, srvf_ae51_n3, srvf_ae201_n0, srvf_ae201_n3))\n  reversal <- (srvf_ae51_n0 > 1 && srvf_ae51_n3 < 1) ||\n    (srvf_ae201_n0 < 1 && srvf_ae201_n3 > 1)\n  if (reversal) {\n    cat(\"The noise-dependent reversal observed for warp MISE is also present for alignment error.\\n\")\n  } else {\n    cat(\"The noise-dependent reversal pattern differs somewhat for alignment error.\\n\")\n  }\n}\n```\n\nSRVF alignment error ratios: grid=51 is 1.69 (noise=0), 0.68 (noise=0.3); grid=201 is 0.97 (noise=0), 1.16 (noise=0.3). The noise-dependent reversal observed for warp MISE is also present for alignment error.\n\n# Grid $\\times$ Noise Interaction {#sec-interaction}\n\nThe key question: does the combination of fine grid + high noise compound for SRVF?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nint_dt <- dt[failure == FALSE,\n  .(\n    warp_mise = median(warp_mise, na.rm = TRUE),\n    q25 = quantile(warp_mise, 0.25, na.rm = TRUE),\n    q75 = quantile(warp_mise, 0.75, na.rm = TRUE)\n  ),\n  by = .(dgp, method, n_grid, noise_sd)\n]\n\nggplot(int_dt, aes(x = n_grid, y = warp_mise, group = dgp, color = dgp)) +\n  geom_line(alpha = 0.7) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = q25, ymax = q75), width = 0.08, alpha = 0.25) +\n  facet_grid(method ~ noise_sd,\n    scales = \"free_y\",\n    labeller = labeller(\n      noise_sd = function(x) paste0(\"noise=\", x),\n      method = mlabs\n    )\n  ) +\n  scale_y_log10() +\n  labs(x = \"Grid size\", y = \"Warp MISE (log scale)\", color = \"DGP\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Grid x noise interaction: warp MISE profiles per method. Points show medians and vertical bars show IQRs; each line connects the 3 grid sizes for one DGP. Steeper upward slopes at grid=201 for noise=0.3 indicate grid-noise compounding. Note: y-axis scales differ across methods due to large baseline differences.](sim-report-grid_files/figure-html/grid-noise-interaction-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Decompose compound effect into main effects + interaction\ncompound_dt <- dt[failure == FALSE,\n  .(warp_mise = median(warp_mise, na.rm = TRUE)),\n  by = .(dgp, method, n_grid, noise_sd)\n]\n\n# For SRVF: decompose the compound ratio\n# Compound = (grid=201, noise=0.3) / (grid=101, noise=0)\n# Noise main effect = (grid=101, noise=0.3) / (grid=101, noise=0)\n# Grid main effect = (grid=201, noise=0) / (grid=101, noise=0)\n# Interaction = compound / (noise_main * grid_main)\n\nref_clean <- compound_dt[n_grid == \"101\" & noise_sd == \"0\",\n  .(dgp, method, ref = warp_mise)]\nnoise_main <- compound_dt[n_grid == \"101\" & noise_sd == \"0.3\",\n  .(dgp, method, noisy = warp_mise)]\ngrid_main <- compound_dt[n_grid == \"201\" & noise_sd == \"0\",\n  .(dgp, method, fine = warp_mise)]\nstress <- compound_dt[n_grid == \"201\" & noise_sd == \"0.3\",\n  .(dgp, method, stressed = warp_mise)]\n\ndecomp <- Reduce(function(a, b) merge(a, b, by = c(\"dgp\", \"method\")),\n  list(ref_clean, noise_main, grid_main, stress))\ndecomp[, `:=`(\n  compound = stressed / ref,\n  noise_effect = noisy / ref,\n  grid_effect = fine / ref,\n  interaction = (stressed / ref) / ((noisy / ref) * (fine / ref))\n)]\n\ncat(\"**Compound effect decomposition** \",\n  \"(grid=201/noise=0.3 vs grid=101/noise=0):\\n\\n\")\n```\n\n**Compound effect decomposition**  (grid=201/noise=0.3 vs grid=101/noise=0):\n\n```{.r .cell-code}\ndecomp_summary <- decomp[,\n  .(\n    compound = median(compound, na.rm = TRUE),\n    noise_main = median(noise_effect, na.rm = TRUE),\n    grid_main = median(grid_effect, na.rm = TRUE),\n    interaction = median(interaction, na.rm = TRUE)\n  ),\n  by = method\n][order(-compound)]\n\ntbl2 <- c(\n  \"| Method | Compound | Noise main | Grid main | Interaction |\",\n  \"|--------|----------|------------|-----------|-------------|\"\n)\nfor (i in seq_len(nrow(decomp_summary))) {\n  tbl2 <- c(tbl2, sprintf(\"| %s | %.1f\\u00d7 | %.1f\\u00d7 | %.2f\\u00d7 | %.2f\\u00d7 |\",\n    mlabs[decomp_summary$method[i]],\n    decomp_summary$compound[i],\n    decomp_summary$noise_main[i],\n    decomp_summary$grid_main[i],\n    decomp_summary$interaction[i]))\n}\ncat(paste(tbl2, collapse = \"\\n\"), \"\\n\\n\")\n```\n\n| Method | Compound | Noise main | Grid main | Interaction |\n|--------|----------|------------|-----------|-------------|\n| SRVF | 21.7× | 13.2× | 0.91× | 1.21× |\n| Landmark (auto) | 1.1× | 1.0× | 1.05× | 0.94× |\n| FDA (crit 1) | 0.8× | 1.0× | 1.06× | 0.78× |\n| FDA (default) | 0.8× | 0.9× | 0.98× | 0.88× |\n| Affine (S+S) | 0.7× | 0.7× | 0.99× | 0.98× | \n\n```{.r .cell-code}\nsrvf_decomp <- decomp_summary[method == \"srvf\"]\ncat(sprintf(\n  \"For SRVF, the compound ratio of %.1f× decomposes into a noise main effect \",\n  srvf_decomp$compound\n))\n```\n\nFor SRVF, the compound ratio of 21.7× decomposes into a noise main effect \n\n```{.r .cell-code}\ncat(sprintf(\n  \"of %.1f×, a grid main effect of %.2f×, and a super-multiplicative interaction \",\n  srvf_decomp$noise_main, srvf_decomp$grid_main\n))\n```\n\nof 13.2×, a grid main effect of 0.91×, and a super-multiplicative interaction \n\n```{.r .cell-code}\ncat(sprintf(\n  \"of %.2f×. \", srvf_decomp$interaction\n))\n```\n\nof 1.21×. \n\n```{.r .cell-code}\nif (srvf_decomp$interaction > 1.1) {\n  cat(\"The interaction exceeds 1, confirming that grid and noise effects \",\n    \"are super-additive for SRVF — fine grids amplify the noise problem \",\n    \"beyond what either factor alone would predict.\\n\\n\")\n} else if (srvf_decomp$interaction < 0.9) {\n  cat(\"The interaction is below 1, suggesting the compound effect is \",\n    \"sub-multiplicative — the large compound ratio is mostly driven by \",\n    \"the noise main effect.\\n\\n\")\n} else {\n  cat(\"The interaction is near 1, suggesting the compound effect is \",\n    \"approximately multiplicative — grid and noise contribute independently \",\n    \"with no synergy.\\n\\n\")\n}\n```\n\nThe interaction exceeds 1, confirming that grid and noise effects  are super-additive for SRVF — fine grids amplify the noise problem  beyond what either factor alone would predict.\n\n```{.r .cell-code}\n# Note on extreme max values\nmax_compound <- decomp[, .(max_compound = max(compound)), by = method]\nextreme <- max_compound[max_compound > 10]\nif (nrow(extreme) > 0) {\n  cat(\"*Note:* Extreme compound ratios (\")\n  cat(paste(sprintf(\"%s: %.0f×\", mlabs[extreme$method], extreme$max_compound),\n    collapse = \", \"))\n  cat(\") are driven by DGPs where the baseline (grid=101, noise=0) warp MISE \",\n    \"is very small, making the ratio sensitive to small absolute differences.\\n\\n\")\n}\n```\n\n*Note:* Extreme compound ratios (SRVF: 202×, Affine (S+S): 54×) are driven by DGPs where the baseline (grid=101, noise=0) warp MISE  is very small, making the ratio sensitive to small absolute differences.\n\n# Per-DGP Profiles {#sec-dgp}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofile_dt <- dt[failure == FALSE,\n  .(\n    median = median(warp_mise, na.rm = TRUE),\n    q25 = quantile(warp_mise, 0.25, na.rm = TRUE),\n    q75 = quantile(warp_mise, 0.75, na.rm = TRUE)\n  ),\n  by = .(dgp, method, n_grid, noise_sd)\n]\n\nggplot(profile_dt, aes(x = n_grid, y = median, color = noise_sd, group = noise_sd)) +\n  geom_line(linewidth = 0.7) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = q25, ymax = q75), width = 0.1, alpha = 0.4) +\n  facet_grid(dgp ~ method, scales = \"free_y\",\n    labeller = labeller(method = mlabs, dgp = dlabs)) +\n  scale_y_log10() +\n  scale_color_brewer(palette = \"Dark2\", name = \"Noise\") +\n  labs(x = \"Grid size\", y = \"Warp MISE (log scale)\") +\n  theme_benchmark(base_size = 9)\n```\n\n::: {.cell-output-display}\n![Per-DGP warp MISE by grid size, faceted by method. Lines connect grid levels within each noise condition. IQR error bars show variability across replications.](sim-report-grid_files/figure-html/dgp-profiles-1.png){width=960}\n:::\n:::\n\n\n# Timing {#sec-timing}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(x = n_grid, y = time_per_curve, fill = n_grid)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n  facet_wrap(~method, nrow = 1, labeller = labeller(method = mlabs)) +\n  scale_y_log10() +\n  scale_fill_brewer(palette = \"Set2\", name = \"Grid size\") +\n  labs(x = \"Grid size\", y = \"Time per curve (sec, log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Computation time per curve (seconds) by grid size and method. Common y-axis (log scale) enables direct comparison. SRVF scales steeply due to O(n²) DP alignment.](sim-report-grid_files/figure-html/timing-1.png){width=1152}\n:::\n:::\n\n\n\n```{.r .cell-code}\ntiming_dt <- dt[failure == FALSE,\n  .(time_per_curve = median(time_per_curve, na.rm = TRUE)),\n  by = .(method, n_grid)\n]\ntiming_wide <- dcast(timing_dt, method ~ n_grid, value.var = \"time_per_curve\")\n\n# Compute timing ratios\ntiming_wide[, ratio_201_101 := `201` / `101`]\ntiming_wide[, method := mlabs[method]]\ncat(\"**Median time per curve (seconds) by method and grid size:**\\n\\n\")\n```\n\n**Median time per curve (seconds) by method and grid size:**\n\n```{.r .cell-code}\nprint(knitr::kable(timing_wide, digits = 4))\n```\n\n\n\n|method          |     51|    101|   201| ratio_201_101|\n|:---------------|------:|------:|-----:|-------------:|\n|SRVF            | 0.0517| 0.1809| 0.705|         3.900|\n|CC (FPC1 cc)    | 0.1130| 0.1171| 0.118|         1.005|\n|CC (L2 dist)    | 0.2074| 0.2057| 0.191|         0.927|\n|Affine (S+S)    | 0.0991| 0.1204| 0.129|         1.074|\n|Landmark (auto) | 0.0033| 0.0036| 0.004|         1.122|\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\nsrvf_ratio <- timing_wide[method == \"SRVF\", ratio_201_101]\ncat(sprintf(\n  \"SRVF timing scales %.1f× from grid=101 to grid=201 (DP alignment is O(n²)). \",\n  srvf_ratio\n))\n```\n\nSRVF timing scales 3.9× from grid=101 to grid=201 (DP alignment is O(n²)). \n\n```{.r .cell-code}\ncat(\"FDA methods show negligible timing change across grid sizes.\\n\")\n```\n\nFDA methods show negligible timing change across grid sizes.\n\n# Summary {#sec-summary}\n\n\n```{.r .cell-code}\n# Summary: for each method, median warp MISE ratio at grid=51 and grid=201 vs 101\nratio_summary_all <- ratio_dt[,\n  .(median_ratio = median(ratio, na.rm = TRUE)),\n  by = .(method, n_grid, noise_sd)\n]\nsummary_wide <- dcast(ratio_summary_all,\n  method + noise_sd ~ n_grid,\n  value.var = \"median_ratio\"\n)\nsummary_wide[, method := mlabs[method]]\ncat(\"**Median warp MISE ratio vs grid=101** (by method and noise level):\\n\\n\")\n```\n\n**Median warp MISE ratio vs grid=101** (by method and noise level):\n\n```{.r .cell-code}\nprint(knitr::kable(summary_wide, digits = 2))\n```\n\n\n\n|method          |noise_sd |   51|  201|\n|:---------------|:--------|----:|----:|\n|SRVF            |0        | 2.26| 0.91|\n|SRVF            |0.1      | 0.93| 1.73|\n|SRVF            |0.3      | 0.73| 1.20|\n|FDA (default)   |0        | 1.00| 0.98|\n|FDA (default)   |0.1      | 1.04| 0.97|\n|FDA (default)   |0.3      | 1.11| 0.88|\n|FDA (crit 1)    |0        | 0.99| 1.06|\n|FDA (crit 1)    |0.1      | 1.10| 0.99|\n|FDA (crit 1)    |0.3      | 1.13| 0.86|\n|Affine (S+S)    |0        | 0.86| 0.99|\n|Affine (S+S)    |0.1      | 0.93| 1.02|\n|Affine (S+S)    |0.3      | 1.05| 1.06|\n|Landmark (auto) |0        | 1.00| 1.05|\n|Landmark (auto) |0.1      | 0.97| 1.01|\n|Landmark (auto) |0.3      | 1.04| 1.00|\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n\n```{.r .cell-code}\ncat(\"**Key findings:**\\n\\n\")\n```\n\n**Key findings:**\n\n```{.r .cell-code}\n# 1. SRVF reversal\nsrvf_51_n0 <- ratio_dt[method == \"srvf\" & n_grid == \"51\" & noise_sd == \"0\",\n  median(ratio, na.rm = TRUE)]\nsrvf_51_n3 <- ratio_dt[method == \"srvf\" & n_grid == \"51\" & noise_sd == \"0.3\",\n  median(ratio, na.rm = TRUE)]\nsrvf_201_n0 <- ratio_dt[method == \"srvf\" & n_grid == \"201\" & noise_sd == \"0\",\n  median(ratio, na.rm = TRUE)]\nsrvf_201_n3 <- ratio_dt[method == \"srvf\" & n_grid == \"201\" & noise_sd == \"0.3\",\n  median(ratio, na.rm = TRUE)]\n\ncat(sprintf(\n  \"1. **SRVF grid sensitivity reverses with noise.** At noise=0, grid=51 \",\n  \"degrades SRVF (%.2f×) while grid=201 helps (%.2f×). At noise=0.3, \",\n  \"grid=51 helps (%.2f×) while grid=201 degrades (%.2f×). Coarse grids \",\n  \"act as implicit regularization by smoothing numerical derivatives.\\n\\n\",\n  srvf_51_n0, srvf_201_n0, srvf_51_n3, srvf_201_n3\n))\n```\n\n1. **SRVF grid sensitivity reverses with noise.** At noise=0, grid=51 \n\n```{.r .cell-code}\n# 2. FDA stability\nfda_def_range <- ratio_dt[method == \"fda_default\",\n  .(lo = min(ratio, na.rm = TRUE), hi = max(ratio, na.rm = TRUE))]\ncat(sprintf(\n  \"2. **FDA methods are grid-insensitive.** fda_default ratios range from \",\n  \"%.2f to %.2f across all grids, noise levels, and DGPs. fda_crit1 shows \",\n  \"slight improvement at finer grids under noise.\\n\\n\",\n  fda_def_range$lo, fda_def_range$hi\n))\n```\n\n2. **FDA methods are grid-insensitive.** fda_default ratios range from \n\n```{.r .cell-code}\n# 3. Timing\ncat(\"3. **SRVF timing scales steeply** (~4× per grid doubling due to O(n²) DP \",\n  \"alignment). FDA timing is essentially constant across grids.\\n\\n\")\n```\n\n3. **SRVF timing scales steeply** (~4× per grid doubling due to O(n²) DP  alignment). FDA timing is essentially constant across grids.\n\n```{.r .cell-code}\n# 4. Practical\ncat(\"4. **Grid=101 is a robust default** for `tf_register()`. It avoids SRVF \",\n  \"degradation at finer grids while providing sufficient resolution for FDA \",\n  \"methods. Users who need finer grids with SRVF should investigate whether \",\n  \"penalization (Study B) can mitigate the derivative noise amplification — \",\n  \"this hypothesis is not tested in Study C.\\n\\n\")\n```\n\n4. **Grid=101 is a robust default** for `tf_register()`. It avoids SRVF  degradation at finer grids while providing sufficient resolution for FDA  methods. Users who need finer grids with SRVF should investigate whether  penalization (Study B) can mitigate the derivative noise amplification —  this hypothesis is not tested in Study C.\n\n```{.r .cell-code}\ncat(\"5. **Grid resolution is a confound for SRVF benchmarking.** \",\n  \"Method comparisons involving SRVF at grid=201 (or finer) \",\n  \"will underestimate SRVF performance relative to FDA methods, especially \",\n  \"under noise. Studies A and B use grid=101, which is neutral territory.\\n\")\n```\n\n5. **Grid resolution is a confound for SRVF benchmarking.**  Method comparisons involving SRVF at grid=201 (or finer)  will underestimate SRVF performance relative to FDA methods, especially  under noise. Studies A and B use grid=101, which is neutral territory.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}