{
  "hash": "594ac68161ff77f3a424276a7cd50209",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Study A: Main Results\"\nsubtitle: \"Registration Benchmark v2\"\n---\n\n# Setup {.unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(data.table)\nlibrary(patchwork)\nlibrary(car)\n\nbase_dir <- here::here()\nsource(file.path(base_dir, \"sim-analyze.R\"))\n\nmcols <- method_colors()\nmlabs <- method_labels()\ndlabs <- dgp_short_labels()\nddesc <- dgp_desc_labels()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndt <- load_study_a()\n```\n:::\n\n\nStudy A compares 5 registration methods across 15 DGPs in a crossed design:\n15 DGPs $\\times$ 2 severity (0.5, 1.0) $\\times$ 3 noise (0, 0.1, 0.3) $\\times$\n5 methods = 450 cells $\\times$ 100 reps = 45,000 runs.\n\nThe DGP design is **not** full factorial (15 of 24 possible template $\\times$ warp\n$\\times$ amplitude combinations), but enables **paired comparisons** that vary\nexactly one factor while holding the other two constant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(\n  dgp_factors(),\n  caption = \"DGP factor structure. 15 DGPs spanning 2 templates, 3 warp types, 4 amplitude types.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: DGP factor structure. 15 DGPs spanning 2 templates, 3 warp types, 4 amplitude types.\n\n|dgp |template |warp_type |amplitude |\n|:---|:--------|:---------|:---------|\n|D01 |harmonic |simple    |none      |\n|D02 |harmonic |complex   |none      |\n|D03 |wiggly   |complex   |none      |\n|D04 |harmonic |affine    |none      |\n|D05 |harmonic |simple    |rank1     |\n|D06 |wiggly   |simple    |rank1     |\n|D07 |harmonic |complex   |rank2     |\n|D08 |wiggly   |complex   |rank2     |\n|D09 |harmonic |simple    |highrank  |\n|D10 |harmonic |complex   |highrank  |\n|D11 |wiggly   |simple    |highrank  |\n|D12 |wiggly   |complex   |highrank  |\n|D13 |wiggly   |affine    |highrank  |\n|D14 |wiggly   |simple    |none      |\n|D15 |harmonic |affine    |highrank  |\n\n\n:::\n:::\n\n\n# DGP Gallery {#sec-gallery}\n\nExample realizations for each DGP (n=20) across 4 conditions. Each row shows\nthe template, the warping functions $h_i(t)$ (dashed = identity), and the resulting\nobserved curves $x_i(t)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions <- function(dgp_name) {\n  make_dgp_example(dgp_name, severity = 0.5, noise_sd = 0,\n                   subtitle = \"sev=0.5, noise=0\") /\n  make_dgp_example(dgp_name, severity = 1.0, noise_sd = 0,\n                   subtitle = \"sev=1.0, noise=0\") /\n  make_dgp_example(dgp_name, severity = 0.5, noise_sd = 0.1,\n                   subtitle = \"sev=0.5, noise=0.1\") /\n  make_dgp_example(dgp_name, severity = 1.0, noise_sd = 0.3,\n                   subtitle = \"sev=1.0, noise=0.3\")\n}\n```\n:::\n\n\n::: {.panel-tabset}\n\n## D01\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D01\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d01-1.png){width=960}\n:::\n:::\n\n\n## D02\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D02\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d02-1.png){width=960}\n:::\n:::\n\n\n## D03\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D03\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d03-1.png){width=960}\n:::\n:::\n\n\n## D04\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D04\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d04-1.png){width=960}\n:::\n:::\n\n\n## D05\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D05\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d05-1.png){width=960}\n:::\n:::\n\n\n## D06\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D06\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d06-1.png){width=960}\n:::\n:::\n\n\n## D07\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D07\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d07-1.png){width=960}\n:::\n:::\n\n\n## D08\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D08\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d08-1.png){width=960}\n:::\n:::\n\n\n## D09\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D09\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d09-1.png){width=960}\n:::\n:::\n\n\n## D10\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D10\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d10-1.png){width=960}\n:::\n:::\n\n\n## D11\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D11\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d11-1.png){width=960}\n:::\n:::\n\n\n## D12\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D12\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d12-1.png){width=960}\n:::\n:::\n\n\n## D13\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D13\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d13-1.png){width=960}\n:::\n:::\n\n\n## D14\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D14\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d14-1.png){width=960}\n:::\n:::\n\n\n## D15\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_dgp_conditions(\"D15\")\n```\n\n::: {.cell-output-display}\n![](sim-report-main_files/figure-html/gallery-d15-1.png){width=960}\n:::\n:::\n\n\n:::\n\n# Overview: DGP $\\times$ Method Heatmaps {#sec-overview}\n\nThe heatmaps below show the **median** of each metric across all 600 runs per cell\n(100 reps $\\times$ 2 severity $\\times$ 3 noise), giving a quick orientation.\nColor encodes the **rank** within each DGP (row): yellow = best (rank 1),\npurple = worst (rank 5). Numeric labels show the actual median values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_heatmap(dt, \"warp_mise\", \"Warp MISE (median, all conditions)\")\n```\n\n::: {.cell-output-display}\n![Median warp MISE across all severity/noise conditions. Color = rank within each DGP; yellow = best, purple = worst. Labels show actual median MISE.](sim-report-main_files/figure-html/heatmap-warp-mise-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_heatmap(dt, \"template_mise\", \"Template MISE (median, all conditions)\")\n```\n\n::: {.cell-output-display}\n![Median template MISE across all severity/noise conditions. Color = rank within each DGP; yellow = best, purple = worst.](sim-report-main_files/figure-html/heatmap-template-mise-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (\"template_elastic_dist\" %in% names(dt) &&\n    any(!is.na(dt$template_elastic_dist))) {\n  make_heatmap(dt, \"template_elastic_dist\",\n    \"Elastic template distance (median, all conditions)\")\n} else {\n  cat(\"*Elastic distance not available — requires re-run with updated sim-run.R.*\")\n}\n```\n\n::: {.cell-output-display}\n![Median elastic (SRSF) template distance across all conditions. Measures template shape quality invariant to reparameterization.](sim-report-main_files/figure-html/heatmap-elastic-dist-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_heatmap(dt, \"alignment_error\", \"Alignment error (median, all conditions)\")\n```\n\n::: {.cell-output-display}\n![Median alignment error across all severity/noise conditions. Color = rank within each DGP; yellow = best, purple = worst.](sim-report-main_files/figure-html/heatmap-alignment-error-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_heatmap(dt, \"alignment_cc\", \"Alignment CC (median, all conditions)\",\n  lower_is_better = FALSE)\n```\n\n::: {.cell-output-display}\n![Median alignment cross-correlation. Color = rank within each DGP; yellow = best, purple = worst.](sim-report-main_files/figure-html/heatmap-alignment-cc-1.png){width=960}\n:::\n:::\n\n\nSince the ANOVA reveals strong method $\\times$ noise interactions (see @sec-anova),\nwe also show noise-conditional warp MISE heatmaps. These reveal how method rankings\nshift between clean and noisy conditions — a pattern hidden by the pooled heatmaps above.\n\n::: {.panel-tabset}\n\n## noise=0\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_heatmap(dt[noise_sd == \"0\"], \"warp_mise\", \"Warp MISE (noise=0)\")\n```\n\n::: {.cell-output-display}\n![Warp MISE at noise=0. SRVF's clean-data advantage is most visible here.](sim-report-main_files/figure-html/heatmap-warp-noise0-1.png){width=960}\n:::\n:::\n\n\n## noise=0.3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_heatmap(dt[noise_sd == \"0.3\"], \"warp_mise\", \"Warp MISE (noise=0.3)\")\n```\n\n::: {.cell-output-display}\n![Warp MISE at noise=0.3. Method rankings shift substantially under high noise.](sim-report-main_files/figure-html/heatmap-warp-noise03-1.png){width=960}\n:::\n:::\n\n\n:::\n\nThe win-rate heatmaps show the percentage of individual runs (across all conditions)\nwhere each method achieves the best metric value among all non-failed methods for\nthat specific run. This complements the median-based heatmaps by revealing how\n*consistently* a method dominates, not just on average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_winrate_heatmap(dt, \"warp_mise\", \"Warp MISE win rate (all conditions)\")\n```\n\n::: {.cell-output-display}\n![Win rate for warp MISE: percentage of runs where each method achieves the lowest warp MISE among all methods, per DGP.](sim-report-main_files/figure-html/heatmap-winrate-warp-mise-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_winrate_heatmap(dt, \"alignment_cc\", \"Alignment CC win rate (all conditions)\",\n  lower_is_better = FALSE)\n```\n\n::: {.cell-output-display}\n![Win rate for alignment CC: percentage of runs where each method achieves the highest cross-correlation.](sim-report-main_files/figure-html/heatmap-winrate-alignment-cc-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\nrank_info <- rank_summary_table(\n  dt = dt,\n  metric = \"warp_mise\",\n  by = c(\"dgp\", \"method\"),\n  rank_within = \"dgp\",\n  stat = \"median\"\n)\nrank_summary <- rank_info$summary[order(mean_rank)]\n\ncat(\"**Key observations** (pooling over severity and noise):\\n\\n\")\n```\n\n**Key observations** (pooling over severity and noise):\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(rank_summary))) {\n  m <- rank_summary$method[i]\n  cat(sprintf(\n    \"- **%s**: mean rank %.1f ± %.1f, rank 1 on %d/%d DGPs, top 2 on %d/%d DGPs.\\n\",\n    mlabs[m], rank_summary$mean_rank[i], rank_summary$se_rank[i],\n    rank_summary$n_rank1[i], uniqueN(dt$dgp),\n    rank_summary$n_top2[i], uniqueN(dt$dgp)\n  ))\n}\n```\n\n- **SRVF**: mean rank 1.8 ± 0.3, rank 1 on 9/15 DGPs, top 2 on 10/15 DGPs.\n- **FDA (default)**: mean rank 2.7 ± 0.3, rank 1 on 4/15 DGPs, top 2 on 6/15 DGPs.\n- **Landmark (auto)**: mean rank 2.9 ± 0.3, rank 1 on 0/15 DGPs, top 2 on 8/15 DGPs.\n- **FDA (crit 1)**: mean rank 3.1 ± 0.2, rank 1 on 0/15 DGPs, top 2 on 4/15 DGPs.\n- **Affine (S+S)**: mean rank 4.5 ± 0.4, rank 1 on 2/15 DGPs, top 2 on 2/15 DGPs.\n\n```{.r .cell-code}\ncat(\"\\n- **Caveat**: These rankings pool over severity and noise levels. Given the strong method:noise interaction (@sec-anova), pooled rankings can be misleading — a method ranking 1st at noise=0 and 4th at noise=0.3 appears as 'mean rank 2.5'. The noise-conditional heatmaps and conditional analyses below provide sharper comparisons.\\n\")\n```\n\n\n- **Caveat**: These rankings pool over severity and noise levels. Given the strong method:noise interaction (@sec-anova), pooled rankings can be misleading — a method ranking 1st at noise=0 and 4th at noise=0.3 appears as 'mean rank 2.5'. The noise-conditional heatmaps and conditional analyses below provide sharper comparisons.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n# Warp Recovery {#sec-warp}\n\n## By warp type (Q1) {#sec-q1}\n\n*Question: Which method best recovers the true warps, conditional on warp type?*\n\n**Warp MISE** measures the integrated squared error between estimated and true warping\nfunctions: $\\text{MISE}_h = \\int_0^1 (\\hat{h}_i(t) - h_i(t))^2\\, dt$, averaged over\ncurves $i$. Lower is better.\n\n**Implementation note:** Warp MISE compares forward warps $\\hat{h}_i$ vs $h_i$\nfor all warp types. Estimated forward warps are recovered by inverting the stored\ninverse warps from `tf_registration`.\n\nWarp types represent fundamentally different problems — smooth elastic warps (simple/complex)\nvs affine warps — so we stratify all comparisons by warp type. Within each stratum,\nwe show the full distribution of warp MISE across all DGPs with that warp type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = warp_mise, fill = method)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n  facet_grid(\n    warp_type ~ severity + noise_sd,\n    scales = \"free_x\",\n    labeller = cond_labeller\n  ) +\n  scale_fill_manual(values = mcols, labels = mlabs, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  labs(y = NULL, x = \"Warp MISE (log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Distribution of warp MISE by method, stratified by warp type (rows). Columns show the 6 severity × noise conditions. Each boxplot summarizes all reps across all DGPs with that warp type.](sim-report-main_files/figure-html/q1-boxplot-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Compute best method per warp type x severity x noise\nq1_ranks <- dt[failure == FALSE,\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(method, warp_type, severity, noise_sd)\n][, rank := rank(mise), by = .(warp_type, severity, noise_sd)]\n\n# Best method per warp type (pooled)\nq1_pooled <- dt[failure == FALSE,\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(method, warp_type)\n][, rank := rank(mise), by = warp_type]\n\nbest_simple <- mlabs[q1_pooled[warp_type == \"simple\"][which.min(mise), method]]\nbest_complex <- mlabs[q1_pooled[warp_type == \"complex\"][which.min(mise), method]]\nbest_affine <- mlabs[q1_pooled[warp_type == \"affine\"][which.min(mise), method]]\n\n# Check ranking stability: does best method stay rank 1 across conditions?\nrank1_simple <- q1_ranks[warp_type == \"simple\" & rank == 1, unique(method)]\nrank1_complex <- q1_ranks[warp_type == \"complex\" & rank == 1, unique(method)]\n\ncat(\"**Findings:**\\n\\n\")\n```\n\n**Findings:**\n\n```{.r .cell-code}\ncat(sprintf(\n  \"- On **simple** warps, %s achieves the lowest median warp MISE (pooled). %s\\n\",\n  best_simple,\n  if (length(rank1_simple) == 1)\n    sprintf(\"This holds across all severity/noise conditions.\")\n  else\n    sprintf(\"The best method varies by condition (%s).\",\n      paste(mlabs[rank1_simple], collapse = \", \"))\n))\n```\n\n- On **simple** warps, SRVF achieves the lowest median warp MISE (pooled). The best method varies by condition (CC (L2 dist), CC (FPC1 cc), SRVF).\n\n```{.r .cell-code}\ncat(sprintf(\n  \"- On **complex** warps, %s achieves the lowest median warp MISE (pooled). %s\\n\",\n  best_complex,\n  if (length(rank1_complex) == 1)\n    sprintf(\"This holds across all severity/noise conditions.\")\n  else\n    sprintf(\"The best method varies by condition (%s).\",\n      paste(mlabs[rank1_complex], collapse = \", \"))\n))\n```\n\n- On **complex** warps, SRVF achieves the lowest median warp MISE (pooled). The best method varies by condition (CC (FPC1 cc), SRVF).\n\n```{.r .cell-code}\ncat(sprintf(\n  \"- On **affine** warps, %s achieves the lowest MISE (see @sec-affine-note).\\n\",\n  best_affine\n))\n```\n\n- On **affine** warps, Affine (S+S) achieves the lowest MISE (see @sec-affine-note).\n\n```{.r .cell-code}\n# Check ranking stability: how often does the rank-1 method stay rank-1 across conditions?\nrank1_all <- q1_ranks[rank == 1, .(n_conditions = .N, methods = paste(unique(method), collapse = \", \")), by = warp_type]\nstable <- rank1_all[n_conditions == length(levels(dt$severity)) * length(levels(dt$noise_sd))]\nif (nrow(stable) == nrow(rank1_all)) {\n  cat(\"- Method rankings are stable: the best method within each warp type holds rank 1 across all severity/noise conditions.\\n\")\n} else {\n  unstable_wt <- setdiff(rank1_all$warp_type, stable$warp_type)\n  for (wt in unstable_wt) {\n    flips <- q1_ranks[warp_type == wt & rank == 1, .(method = method, cond = paste0(\"sev=\", severity, \"/noise=\", noise_sd))]\n    cat(sprintf(\"- On **%s** warps, the rank-1 method changes across conditions: %s.\\n\",\n      wt, paste(sprintf(\"%s at %s\", mlabs[flips$method], flips$cond), collapse = \"; \")))\n  }\n}\n```\n\n- Method rankings are stable: the best method within each warp type holds rank 1 across all severity/noise conditions.\n\n```{.r .cell-code}\n# Check FDA tail behavior\nfda_iqr <- dt[failure == FALSE & method == \"cc_default\",\n  .(iqr = IQR(warp_mise, na.rm = TRUE)), by = warp_type]\nsrvf_iqr <- dt[failure == FALSE & method == \"srvf\",\n  .(iqr = IQR(warp_mise, na.rm = TRUE)), by = warp_type]\nif (all(fda_iqr$iqr > srvf_iqr$iqr)) {\n  cat(\"- FDA methods show competitive medians but heavier tails (more variable performance).\\n\")\n}\n```\n\n- FDA methods show competitive medians but heavier tails (more variable performance).\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq1_summary <- mc_summary(dt, warp_mise,\n  by = c(\"method\", \"warp_type\", \"severity\", \"noise_sd\"))\nq1_summary[, cell := sprintf(\"%s [%s, %s]\", fmt(median), fmt(q25), fmt(q75))]\nq1_wide <- dcast(\n  q1_summary[, .(method, warp_type, severity, noise_sd, cell)],\n  method + warp_type ~ severity + noise_sd,\n  value.var = \"cell\"\n)\nknitr::kable(\n  q1_wide[order(warp_type, method)],\n  caption = \"Median warp MISE [Q25, Q75] by method, warp type, severity, and noise level, pooling over DGPs within each warp type.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Median warp MISE [Q25, Q75] by method, warp type, severity, and noise level, pooling over DGPs within each warp type.\n\n|method        |warp_type |0.5_0                      |0.5_0.1                    |0.5_0.3                    |1_0                        |1_0.1                      |1_0.3                      |\n|:-------------|:---------|:--------------------------|:--------------------------|:--------------------------|:--------------------------|:--------------------------|:--------------------------|\n|srvf          |affine    |2.1e-04 [1.4e-04, 9.2e-04] |6.8e-04 [3.4e-04, 8.6e-04] |0.00192 [0.001, 0.00228]   |0.00124 [7.3e-04, 0.00181] |0.00153 [0.00126, 0.00186] |0.00481 [0.00264, 0.00615] |\n|fda_default   |affine    |0.00159 [3.1e-04, 0.00245] |0.00161 [3.4e-04, 0.00228] |0.00151 [4.7e-04, 0.00206] |0.00331 [0.00125, 0.0127]  |0.00347 [0.00125, 0.0131]  |0.0034 [0.00157, 0.0103]   |\n|fda_crit1     |affine    |0.00151 [3.0e-04, 0.00216] |0.0015 [3.3e-04, 0.00223]  |0.00138 [4.5e-04, 0.00203] |0.00558 [0.00162, 0.0107]  |0.00471 [0.0017, 0.00862]  |0.00353 [0.00149, 0.00778] |\n|affine_ss     |affine    |2.6e-04 [2.2e-06, 0.0183]  |2.6e-04 [1.2e-05, 0.0182]  |3.9e-04 [1.6e-04, 0.0101]  |7.4e-04 [1.2e-05, 0.0801]  |8.1e-04 [2.2e-05, 0.0834]  |0.00156 [5.1e-04, 0.0922]  |\n|landmark_auto |affine    |6.9e-04 [4.6e-04, 0.00253] |6.4e-04 [4.1e-04, 0.00257] |0.00106 [8.5e-04, 0.00307] |0.00517 [0.00394, 0.00693] |0.00495 [0.00354, 0.00663] |0.00559 [0.00403, 0.00728] |\n|srvf          |simple    |1.2e-05 [9.7e-06, 5.3e-05] |5.6e-04 [1.1e-04, 8.7e-04] |0.00369 [9.4e-04, 0.00645] |1.9e-04 [8.3e-05, 5.3e-04] |0.00153 [3.4e-04, 0.00384] |0.0179 [0.00815, 0.0223]   |\n|fda_default   |simple    |0.0032 [3.5e-05, 0.00898]  |0.00272 [4.3e-05, 0.0076]  |0.00225 [1.5e-04, 0.00589] |0.0146 [0.00367, 0.023]    |0.0139 [0.00342, 0.0226]   |0.0136 [0.00307, 0.0219]   |\n|fda_crit1     |simple    |0.00633 [0.00164, 0.0141]  |0.00509 [0.00163, 0.0137]  |0.00384 [0.00143, 0.0102]  |0.0139 [0.0031, 0.0377]    |0.0158 [0.00279, 0.0405]   |0.0121 [0.00223, 0.0381]   |\n|affine_ss     |simple    |0.021 [0.00526, 0.0802]    |0.0208 [0.00403, 0.0904]   |0.0238 [0.00335, 0.1]      |0.112 [0.0715, 0.198]      |0.118 [0.0714, 0.217]      |0.0971 [0.0526, 0.21]      |\n|landmark_auto |simple    |0.00553 [0.00204, 0.00856] |0.00561 [0.00207, 0.00861] |0.00711 [0.00426, 0.0086]  |0.0192 [0.015, 0.0224]     |0.02 [0.0168, 0.0225]      |0.0218 [0.0193, 0.0242]    |\n|srvf          |complex   |3.0e-05 [1.6e-05, 6.9e-05] |1.0e-03 [3.0e-04, 0.00159] |0.00328 [0.00173, 0.00479] |4.7e-04 [2.7e-04, 0.00132] |0.00523 [0.00294, 0.0107]  |0.0152 [0.0109, 0.0176]    |\n|fda_default   |complex   |0.00413 [0.00219, 0.00933] |0.00375 [0.00223, 0.00891] |0.00336 [0.00209, 0.0068]  |0.016 [0.00726, 0.024]     |0.0157 [0.00708, 0.023]    |0.0142 [0.00604, 0.021]    |\n|fda_crit1     |complex   |0.00388 [0.00264, 0.00692] |0.00394 [0.00255, 0.00662] |0.00337 [0.00228, 0.0056]  |0.0177 [0.00972, 0.0293]   |0.0161 [0.00846, 0.0302]   |0.0144 [0.00768, 0.0281]   |\n|affine_ss     |complex   |0.0118 [0.00289, 0.0528]   |0.0109 [0.00258, 0.0606]   |0.0106 [0.00227, 0.0594]   |0.085 [0.0445, 0.18]       |0.0914 [0.0383, 0.178]     |0.0675 [0.0293, 0.145]     |\n|landmark_auto |complex   |0.00398 [0.00207, 0.00616] |0.00378 [0.00178, 0.00604] |0.00451 [0.00258, 0.00579] |0.0148 [0.0125, 0.017]     |0.0156 [0.0138, 0.0174]    |0.0166 [0.0153, 0.0182]    |\n\n\n:::\n:::\n\n\n## Phase-amplitude interaction (Q2) {#sec-q2}\n\n*Question: Does amplitude variation degrade warp recovery?*\n\nWe use **amplitude ladders** — sequences of DGPs that hold template and warp type constant\nwhile increasing amplitude complexity (none $\\to$ rank-1 $\\to$ rank-2 $\\to$ high-rank).\nAn upward slope means that method's warp recovery degrades as amplitude complexity increases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nladders <- amplitude_ladders()\nplots <- lapply(names(ladders), function(nm) {\n  make_ladder_plot(dt, ladders[[nm]], nm)\n})\nwrap_plots(plots, ncol = 1) +\n  plot_layout(guides = \"collect\") &\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Amplitude ladders: median warp MISE (IQR error bars) vs amplitude complexity. Each panel row holds template and warp type fixed; columns show the 6 severity × noise conditions. Upward slopes indicate degraded warp recovery under amplitude variation.](sim-report-main_files/figure-html/q2-ladders-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Check degradation on each ladder: does MISE go up with amplitude complexity?\nladders_q2 <- amplitude_ladders()\n\ncat(\"**Findings:**\\n\\n\")\n```\n\n**Findings:**\n\n```{.r .cell-code}\n# Count how often each method degrades vs improves across ladders and conditions\nn_degrade <- 0L\nn_improve <- 0L\nn_total <- 0L\nfor (lnm in names(ladders_q2)) {\n  ld <- ladders_q2[[lnm]]\n  dgps <- names(ld)\n  first_dgp <- dgps[1]\n  last_dgp <- dgps[length(dgps)]\n  for (m in levels(dt$method)) {\n    for (s in levels(dt$severity)) {\n      for (ns in levels(dt$noise_sd)) {\n        v_first <- dt[dgp == first_dgp & method == m & severity == s &\n          noise_sd == ns & failure == FALSE, median(warp_mise, na.rm = TRUE)]\n        v_last <- dt[dgp == last_dgp & method == m & severity == s &\n          noise_sd == ns & failure == FALSE, median(warp_mise, na.rm = TRUE)]\n        if (length(v_first) && length(v_last) && !is.na(v_first) && !is.na(v_last)) {\n          n_total <- n_total + 1L\n          if (v_last > v_first) n_degrade <- n_degrade + 1L\n          else n_improve <- n_improve + 1L\n        }\n      }\n    }\n  }\n}\n\npct_degrade <- round(100 * n_degrade / n_total)\nif (pct_degrade > 70) {\n  amp_txt <- \"The pattern is predominant — higher-rank amplitude generally makes warp recovery harder.\"\n} else if (pct_degrade > 50) {\n  amp_txt <- \"The pattern holds for most cases but has notable exceptions — some methods on some ladders show stable or slightly improved MISE under higher-rank amplitude.\"\n} else {\n  amp_txt <- \"The pattern is **inconsistent** — higher-rank amplitude does not systematically degrade warp recovery across methods and conditions.\"\n}\ncat(sprintf(\n  \"- In %d%% of method-ladder-condition comparisons (%d/%d), warp MISE is higher at the most complex amplitude than at the baseline (endpoint comparison, not monotonicity). %s\\n\",\n  pct_degrade, n_degrade, n_total, amp_txt\n))\n```\n\n- In 86% of method-ladder-condition comparisons (103/120), warp MISE is higher at the most complex amplitude than at the baseline (endpoint comparison, not monotonicity). The pattern is predominant — higher-rank amplitude generally makes warp recovery harder.\n\n```{.r .cell-code}\n# Check which method has best absolute MISE at highrank\nbest_highrank <- dt[failure == FALSE & amplitude == \"highrank\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = method][which.min(mise), method]\ncat(sprintf(\n  \"- **%s** generally retains the lowest absolute MISE as amplitude complexity grows, though its *relative* degradation can be comparable to other methods.\\n\",\n  mlabs[best_highrank]\n))\n```\n\n- **SRVF** generally retains the lowest absolute MISE as amplitude complexity grows, though its *relative* degradation can be comparable to other methods.\n\n```{.r .cell-code}\ncat(\"- The magnitude and direction of amplitude effects vary across ladders and conditions — see the plots above for per-ladder details.\\n\")\n```\n\n- The magnitude and direction of amplitude effects vary across ladders and conditions — see the plots above for per-ladder details.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n## Warp complexity effect (Q3) {#sec-q3}\n\n*Question: How much does warp complexity cost each method?*\n\n**Warp ladders** hold template and amplitude constant while increasing warp complexity\n(affine $\\to$ simple $\\to$ complex).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nladders_w <- warp_ladders()\nplots_w <- lapply(names(ladders_w), function(nm) {\n  make_ladder_plot(dt, ladders_w[[nm]], nm)\n})\nwrap_plots(plots_w, ncol = 1) +\n  plot_layout(guides = \"collect\") &\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Warp ladders: median warp MISE (IQR error bars) vs warp complexity. Each panel row holds template and amplitude fixed; columns show the 6 severity × noise conditions.](sim-report-main_files/figure-html/q3-ladders-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Check how often complex > simple MISE across methods and conditions\nladders_w <- warp_ladders()\nn_worse <- 0L\nn_better <- 0L\nn_tot_q3 <- 0L\nfor (lnm in names(ladders_w)) {\n  ld <- ladders_w[[lnm]]\n  dgps <- names(ld)\n  if (!(\"simple\" %in% ld && \"complex\" %in% ld)) next\n  d_simple <- names(ld)[ld == \"simple\"]\n  d_complex <- names(ld)[ld == \"complex\"]\n  for (m in levels(dt$method)) {\n    for (s in levels(dt$severity)) {\n      for (ns in levels(dt$noise_sd)) {\n        v_s <- dt[dgp == d_simple & method == m & severity == s &\n          noise_sd == ns & failure == FALSE, median(warp_mise, na.rm = TRUE)]\n        v_c <- dt[dgp == d_complex & method == m & severity == s &\n          noise_sd == ns & failure == FALSE, median(warp_mise, na.rm = TRUE)]\n        if (length(v_s) && length(v_c) && !is.na(v_s) && !is.na(v_c)) {\n          n_tot_q3 <- n_tot_q3 + 1L\n          if (v_c > v_s) n_worse <- n_worse + 1L\n          else n_better <- n_better + 1L\n        }\n      }\n    }\n  }\n}\npct_worse <- round(100 * n_worse / n_tot_q3)\n\ncat(\"**Findings:**\\n\\n\")\n```\n\n**Findings:**\n\n```{.r .cell-code}\nif (pct_worse > 60) {\n  q3_txt <- \"The effect is predominant — complex warps are harder to recover for most methods and conditions.\"\n} else if (pct_worse > 40) {\n  q3_txt <- \"The effect is **inconsistent** — complex warps are not systematically harder to recover. The direction depends on the method, template type, and noise level.\"\n} else {\n  q3_txt <- \"Counter to expectation, simple warps tend to produce higher MISE.\"\n}\ncat(sprintf(\n  \"- In %d%% of comparisons (%d/%d), complex warps yield higher MISE than simple warps. %s\\n\",\n  pct_worse, n_worse, n_tot_q3, q3_txt\n))\n```\n\n- In 43% of comparisons (52/120), complex warps yield higher MISE than simple warps. The effect is **inconsistent** — complex warps are not systematically harder to recover. The direction depends on the method, template type, and noise level.\n\n```{.r .cell-code}\n# Check affine DGPs\naffine_dgps <- dgp_factors()[warp_type == \"affine\", dgp]\nif (length(affine_dgps) > 0) {\n  affine_ranks <- dt[failure == FALSE & dgp %in% affine_dgps,\n    .(mise = median(warp_mise, na.rm = TRUE)),\n    by = method][order(mise)]\n  affine_best <- mlabs[affine_ranks$method[1]]\n  affine_worst <- mlabs[affine_ranks$method[.N]]\n  affine_ss_rank <- which(affine_ranks$method == \"affine_ss\")\n  cat(sprintf(\n    \"- On **affine** DGPs: %s achieves the lowest MISE (rank %d of %d). See @sec-affine-note.\\n\",\n    affine_best, affine_ss_rank, nrow(affine_ranks)\n  ))\n}\n```\n\n- On **affine** DGPs: Affine (S+S) achieves the lowest MISE (rank 1 of 5). See @sec-affine-note.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n### Affine warp performance {#sec-affine-note}\n\n\n```{.r .cell-code}\naffine_dgps <- dgp_factors()[warp_type == \"affine\", dgp]\naffine_data <- dt[failure == FALSE & dgp %in% affine_dgps,\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = method][order(mise)]\naffine_ss_mise <- affine_data[method == \"affine_ss\", mise]\nbest_mise <- affine_data$mise[1]\n\nif (affine_data$method[1] == \"affine_ss\") {\n  second_mise <- affine_data$mise[2]\n  ratio_vs_2nd <- round(second_mise / best_mise, 1)\n  cat(sprintf(\n    \"On %s (the affine DGPs), **Affine (S+S)** achieves the lowest median warp MISE — %.1f$\\\\times$ lower than %s. The well-specified parametric model outperforms nonparametric alternatives, as expected.\\n\\n\",\n    paste(affine_dgps, collapse = \", \"),\n    ratio_vs_2nd,\n    mlabs[affine_data$method[2]]\n  ))\n  cat(\"However, Affine (S+S) has the **highest warp MISE on non-affine DGPs** — it is misspecified for smooth elastic warps and pays a large penalty. This highlights the usual bias-variance trade-off: the parametric model wins when correctly specified but loses when not.\\n\")\n} else {\n  ratio_vs_best <- round(affine_ss_mise / best_mise, 1)\n  cat(sprintf(\n    \"On %s (the affine DGPs), Affine (S+S) is well-specified but achieves %.1f$\\\\times$ higher MISE than %s. Possible explanations include template estimation bias and limited signal at low severity. Study C (oracle template) can test this.\\n\",\n    paste(affine_dgps, collapse = \", \"),\n    ratio_vs_best,\n    mlabs[affine_data$method[1]]\n  ))\n}\n```\n\nOn D04, D13, D15 (the affine DGPs), **Affine (S+S)** achieves the lowest median warp MISE — 2.4$\\times$ lower than SRVF. The well-specified parametric model outperforms nonparametric alternatives, as expected.\n\nHowever, Affine (S+S) has the **highest warp MISE on non-affine DGPs** — it is misspecified for smooth elastic warps and pays a large penalty. This highlights the usual bias-variance trade-off: the parametric model wins when correctly specified but loses when not.\n\n\n## Alignment error {#sec-alignment-error}\n\n*How well do registered curves match the true pre-warp curves?*\n\n**Alignment error** measures $\\text{mean}_i \\int_0^1 (\\hat{x}_i^{\\text{aligned}}(t) - \\tilde{x}_i(t))^2\\,dt$\nwhere $\\hat{x}_i^{\\text{aligned}}$ is the registered curve and $\\tilde{x}_i = \\mu \\circ h_i + a_i$\nis the true pre-warp curve. This captures the practical impact of registration error\non downstream analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = alignment_error, fill = method)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n  facet_grid(\n    warp_type ~ severity + noise_sd,\n    scales = \"free_x\",\n    labeller = cond_labeller\n  ) +\n  scale_fill_manual(values = mcols, labels = mlabs, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  labs(y = NULL, x = \"Alignment error (log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Distribution of alignment error by method, stratified by warp type (rows) and severity × noise (columns).](sim-report-main_files/figure-html/alignment-error-boxplot-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\nae_ranks <- dt[failure == FALSE,\n  .(ae = median(alignment_error, na.rm = TRUE)),\n  by = .(method, warp_type, severity, noise_sd)\n][, rank := rank(ae), by = .(warp_type, severity, noise_sd)]\n\nae_pooled <- dt[failure == FALSE,\n  .(ae = median(alignment_error, na.rm = TRUE)),\n  by = .(method, warp_type)\n][, rank := rank(ae), by = warp_type]\n\n# Check correlation with warp MISE\nae_vs_warp <- dt[failure == FALSE,\n  .(ae = median(alignment_error, na.rm = TRUE),\n    mise = median(warp_mise, na.rm = TRUE)),\n  by = .(method, dgp, severity, noise_sd)]\nr_cor <- cor(log(ae_vs_warp$ae), log(ae_vs_warp$mise), use = \"complete.obs\")\n\ncat(\"**Findings:**\\n\\n\")\n```\n\n**Findings:**\n\n```{.r .cell-code}\ncat(sprintf(\"- Alignment error and warp MISE are strongly correlated (r = %.2f on log scale). \", r_cor))\n```\n\n- Alignment error and warp MISE are strongly correlated (r = 0.83 on log scale). \n\n```{.r .cell-code}\nif (abs(r_cor) > 0.9) {\n  cat(\"The two metrics tell essentially the same story — good warp recovery implies good alignment.\\n\")\n} else {\n  cat(\"The correlation is substantial but imperfect — some methods achieve better alignment than their warp accuracy alone would predict.\\n\")\n}\n```\n\nThe correlation is substantial but imperfect — some methods achieve better alignment than their warp accuracy alone would predict.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\nfor (wt in c(\"simple\", \"complex\", \"affine\")) {\n  best_ae <- ae_pooled[warp_type == wt][which.min(ae)]\n  cat(sprintf(\"- **%s** warps: %s achieves the lowest alignment error.\\n\",\n    wt, mlabs[best_ae$method]))\n}\n```\n\n- **simple** warps: SRVF achieves the lowest alignment error.\n- **complex** warps: SRVF achieves the lowest alignment error.\n- **affine** warps: Affine (S+S) achieves the lowest alignment error.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n## Method × template interaction {#sec-method-template}\n\nThe ANOVA identifies method:template as a major interaction term. The plot below\nshows how method performance differs between harmonic and wiggly templates — a\npattern hidden when pooling over templates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmt_agg <- dt[failure == FALSE & warp_type != \"affine\",\n  .(\n    mise = median(warp_mise, na.rm = TRUE),\n    q25 = quantile(warp_mise, 0.25, na.rm = TRUE),\n    q75 = quantile(warp_mise, 0.75, na.rm = TRUE)\n  ),\n  by = .(method, template, noise_sd)]\n\nggplot(mt_agg, aes(x = template, y = mise, color = method, group = method)) +\n  geom_line(linewidth = 0.8) +\n  geom_point(size = 2.5) +\n  geom_errorbar(aes(ymin = q25, ymax = q75), width = 0.08, alpha = 0.35) +\n  facet_wrap(~ noise_sd, labeller = labeller(\n    noise_sd = function(x) paste0(\"noise=\", x))) +\n  scale_color_manual(values = mcols, labels = mlabs) +\n  scale_y_log10() +\n  labs(x = \"Template\", y = \"Median warp MISE (log scale)\", color = \"Method\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Method × template interaction for warp MISE. Points show medians and vertical bars show IQRs. Lines connect the same method across template types. Crossing lines indicate rank reversals between templates.](sim-report-main_files/figure-html/method-template-interaction-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Check for rank reversals between templates\nmt_ranks <- mt_agg[, .(best = method[which.min(mise)]), by = .(template, noise_sd)]\nmt_wide <- dcast(mt_ranks, noise_sd ~ template, value.var = \"best\")\n\ncat(\"**Findings:**\\n\\n\")\n```\n\n**Findings:**\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(mt_wide))) {\n  ns <- mt_wide$noise_sd[i]\n  h_best <- mlabs[mt_wide$harmonic[i]]\n  w_best <- mlabs[mt_wide$wiggly[i]]\n  if (mt_wide$harmonic[i] == mt_wide$wiggly[i]) {\n    cat(sprintf(\"- noise=%s: %s ranks first on both templates.\\n\", ns, h_best))\n  } else {\n    cat(sprintf(\"- noise=%s: **rank reversal** — %s best on harmonic, %s best on wiggly.\\n\",\n      ns, h_best, w_best))\n  }\n}\n```\n\n- noise=0: SRVF ranks first on both templates.\n- noise=0.1: SRVF ranks first on both templates.\n- noise=0.3: **rank reversal** — FDA (default) best on harmonic, SRVF best on wiggly.\n\n```{.r .cell-code}\ncat(\"\\nThis interaction means that 'best method' claims depend on the template type. Pooled rankings favor whichever template type dominates the average.\\n\\n\")\n```\n\n\nThis interaction means that 'best method' claims depend on the template type. Pooled rankings favor whichever template type dominates the average.\n\n# Registration Diagnostics {#sec-diag}\n\n## Over/under-registration (Q4) {#sec-q4}\n\n*Question: Do methods systematically over-register or under-register?*\n\nThe **registration ratio** measures how much the estimated warp deviates from\nthe identity relative to the true warp:\n$$R_i = \\frac{\\|\\hat{h}_i - \\mathrm{id}\\|^2}{\\|h_i - \\mathrm{id}\\|^2}$$\nwhere $\\|\\cdot\\|^2 = \\int_0^1 (\\cdot)^2\\,dt$.\nValues $R < 1$ indicate under-registration (estimated warp closer to identity\nthan truth); $R > 1$ indicates over-registration (warped too much).\nWe report the median $R$ across curves within each run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_reg_ratio_plot(dt)\n```\n\n::: {.cell-output-display}\n![Registration ratio by method, stratified by warp type (rows) and severity × noise (columns). Each dot = one DGP (median over 100 reps); crossbar = median across DGPs. Dashed line at 1 = perfectly calibrated.](sim-report-main_files/figure-html/q4-reg-ratio-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrr_agg <- dt[\n  failure == FALSE & !is.na(registration_ratio_median) &\n    severity == \"0.5\",\n  .(\n    median_rr = median(registration_ratio_median, na.rm = TRUE),\n    q25 = quantile(registration_ratio_median, 0.25, na.rm = TRUE),\n    q75 = quantile(registration_ratio_median, 0.75, na.rm = TRUE)\n  ),\n  by = .(method, warp_type, noise_sd)\n]\n\nggplot(rr_agg, aes(y = method, x = median_rr, color = method)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n  geom_point(size = 3) +\n  geom_errorbarh(aes(xmin = q25, xmax = q75), height = 0.2) +\n  facet_grid(noise_sd ~ warp_type,\n    labeller = labeller(noise_sd = function(x) paste0(\"noise=\", x))) +\n  scale_color_manual(values = mcols, labels = mlabs, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_continuous(trans = \"log2\",\n    breaks = c(0.25, 0.5, 1, 2, 4),\n    labels = c(\"1/4\", \"1/2\", \"1\", \"2\", \"4\")) +\n  labs(y = NULL, x = expression(\"Registration ratio (\" * log[2] * \" scale)\")) +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Registration ratio aggregated by method, warp type (columns), and noise level (rows). Severity=0.5. Median and IQR across all DGPs within each warp type.](sim-report-main_files/figure-html/q4-reg-ratio-aggregated-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Compute registration ratio by method x warp_type x noise_sd\nrr_by_mwn <- dt[\n  failure == FALSE & !is.na(registration_ratio_median),\n  .(rr = median(registration_ratio_median, na.rm = TRUE)),\n  by = .(method, warp_type, noise_sd)\n]\n\ncat(\"**Findings** (registration ratio, pooled over severity):\\n\\n\")\n```\n\n**Findings** (registration ratio, pooled over severity):\n\n```{.r .cell-code}\nfor (ns in levels(dt$noise_sd)) {\n  cat(sprintf(\"*noise=%s:*\\n\\n\", ns))\n  rr_sub <- rr_by_mwn[noise_sd == ns]\n  for (m in levels(dt$method)) {\n    vals <- rr_sub[method == m]\n    if (nrow(vals) == 0) next\n    parts <- paste(\n      sprintf(\"%s: %.2f\", vals$warp_type, vals$rr),\n      collapse = \", \"\n    )\n    # Classify overall behavior\n    med_rr <- median(vals$rr)\n    behavior <- if (med_rr < 0.8) {\n      \"under-registers\"\n    } else if (med_rr > 1.2) {\n      \"over-registers\"\n    } else {\n      \"near-calibrated\"\n    }\n    cat(sprintf(\"- **%s** (%s): %s\\n\", mlabs[m], behavior, parts))\n  }\n  cat(\"\\n\")\n}\n```\n\n*noise=0:*\n\n- **SRVF** (near-calibrated): simple: 0.99, complex: 0.98, affine: 0.94\n- **FDA (default)** (over-registers): simple: 1.16, complex: 1.32, affine: 1.68\n- **FDA (crit 1)** (over-registers): simple: 1.33, complex: 1.33, affine: 1.36\n- **Affine (S+S)** (near-calibrated): simple: 1.40, complex: 1.11, affine: 1.06\n- **Landmark (auto)** (under-registers): simple: 0.27, complex: 0.27, affine: 0.66\n\n*noise=0.1:*\n\n- **SRVF** (near-calibrated): simple: 0.96, complex: 0.87, affine: 1.00\n- **FDA (default)** (over-registers): simple: 1.10, complex: 1.27, affine: 1.65\n- **FDA (crit 1)** (over-registers): simple: 1.33, complex: 1.32, affine: 1.29\n- **Affine (S+S)** (near-calibrated): simple: 1.33, complex: 1.04, affine: 1.05\n- **Landmark (auto)** (under-registers): simple: 0.29, complex: 0.28, affine: 0.70\n\n*noise=0.3:*\n\n- **SRVF** (under-registers): simple: 0.54, complex: 0.51, affine: 0.89\n- **FDA (default)** (near-calibrated): simple: 1.05, complex: 1.09, affine: 1.34\n- **FDA (crit 1)** (near-calibrated): simple: 1.22, complex: 1.13, affine: 1.06\n- **Affine (S+S)** (near-calibrated): simple: 0.88, complex: 0.60, affine: 1.02\n- **Landmark (auto)** (under-registers): simple: 0.32, complex: 0.32, affine: 0.75\n\nThe **warp slope ratio** measures how much \"wiggliness\" the estimated warp has\nrelative to the truth:\n$$S_i = \\frac{\\max \\hat{h}_i'(t) - \\min \\hat{h}_i'(t)}{\\max h_i'(t) - \\min h_i'(t)}$$\nValues $S > 1$ mean the estimated warp is too wiggly; $S < 1$ means too smooth.\nThis diagnostic is only meaningful for non-affine warps (affine warps have\nconstant derivative, making the denominator uninformative).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndt_slope <- dt[\n  warp_type != \"affine\" & failure == FALSE & !is.na(warp_slope_ratio_median)\n]\nif (nrow(dt_slope) > 0) {\n  slope_agg <- dt_slope[, .(\n    median_sr = median(warp_slope_ratio_median, na.rm = TRUE),\n    q25 = quantile(warp_slope_ratio_median, 0.25, na.rm = TRUE),\n    q75 = quantile(warp_slope_ratio_median, 0.75, na.rm = TRUE)\n  ), by = .(method, warp_type, template)]\n\n  ggplot(slope_agg, aes(y = method, x = median_sr, color = method)) +\n    geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n    geom_point(size = 3) +\n    geom_errorbarh(aes(xmin = q25, xmax = q75), height = 0.2) +\n    facet_grid(template ~ warp_type) +\n    scale_color_manual(values = mcols, labels = mlabs, guide = \"none\") +\n    scale_y_discrete(labels = mlabs) +\n    scale_x_continuous(trans = \"log2\") +\n    labs(y = NULL, x = expression(\"Warp slope ratio (\" * log[2] * \" scale)\")) +\n    theme_benchmark()\n}\n```\n\n::: {.cell-output-display}\n![Warp slope ratio by method, warp type (columns), and template type (rows). Non-affine DGPs only. Median and IQR across noise and severity conditions. Values > 1 = estimated warps too wiggly; < 1 = too smooth.](sim-report-main_files/figure-html/q4-warp-slope-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Compute warp slope ratio by method x warp_type x template\nsr_by_mwt <- dt[\n  warp_type != \"affine\" & failure == FALSE & !is.na(warp_slope_ratio_median),\n  .(sr = median(warp_slope_ratio_median, na.rm = TRUE)),\n  by = .(method, warp_type, template)\n]\n\ncat(\"**Warp slope findings:**\\n\\n\")\n```\n\n**Warp slope findings:**\n\n```{.r .cell-code}\nfor (m in levels(dt$method)) {\n  vals <- sr_by_mwt[method == m]\n  if (nrow(vals) == 0) next\n  parts <- paste(\n    sprintf(\"%s/%s: %.2f\", vals$template, vals$warp_type, vals$sr),\n    collapse = \", \"\n  )\n  cat(sprintf(\"- **%s**: %s\\n\", mlabs[m], parts))\n}\n```\n\n- **SRVF**: harmonic/simple: 2.97, harmonic/complex: 1.07, wiggly/complex: 1.10, wiggly/simple: 2.86\n- **FDA (default)**: harmonic/simple: 1.01, harmonic/complex: 0.46, wiggly/complex: 0.63, wiggly/simple: 1.61\n- **FDA (crit 1)**: harmonic/simple: 1.40, harmonic/complex: 0.55, wiggly/complex: 0.49, wiggly/simple: 1.88\n- **Affine (S+S)**: harmonic/simple: 0.00, harmonic/complex: 0.00, wiggly/complex: 0.00, wiggly/simple: 0.00\n- **Landmark (auto)**: harmonic/simple: 0.68, harmonic/complex: 0.23, wiggly/complex: 0.49, wiggly/simple: 1.14\n\n```{.r .cell-code}\ncat(\"\\nValues > 1 indicate estimated warps are wigglier than truth; < 1 indicates smoother.\\n\\n\")\n```\n\n\nValues > 1 indicate estimated warps are wigglier than truth; < 1 indicates smoother.\n\n\n## Phase-amplitude separation (Q2b) {#sec-amp-ratio}\n\n*Question: Do methods confuse phase and amplitude variation?*\n\nThe **amplitude variance ratio** compares the residual amplitude variance after\nregistration to the true amplitude variance:\n$$\\text{AVR} = \\frac{\\overline{\\text{Var}}_t\\bigl(\\hat{x}_i^{\\text{aligned}}(t) - \\hat{\\mu}(t)\\bigr)}{\\overline{\\text{Var}}_t\\bigl(\\tilde{x}_i(t) - \\mu(t)\\bigr)}$$\nwhere $\\hat{\\mu}$ is the estimated template, $\\tilde{x}_i = \\mu \\circ h_i + a_i$ is\nthe true pre-warp curve (template composed with true warp, plus true amplitude\ncomponent $a_i$), and $\\overline{\\text{Var}}_t$ denotes the pointwise variance\nacross curves $i$, averaged over $t$. Thus the numerator measures the residual\ncurve-to-curve variation after registration, and the denominator measures the\ntrue amplitude variation in the DGP.\n\n- $\\text{AVR} < 1$ suggests **over-registration**: the method absorbed some\n  amplitude variation into the phase component.\n- $\\text{AVR} > 1$ suggests **under-registration**: residual phase variation\n  remains in the amplitude component, or the estimated template differs from\n  the truth, inflating residuals.\n\nThis diagnostic is only shown for DGPs with amplitude variation (D05--D13).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndt_amp <- dt[amplitude != \"none\" & failure == FALSE & !is.na(amp_variance_ratio)]\n\nif (nrow(dt_amp) > 0) {\n  ggplot(dt_amp, aes(y = method, x = amp_variance_ratio, fill = method)) +\n    geom_vline(xintercept = 1, linetype = \"dashed\", color = \"grey40\") +\n    geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n    facet_grid(\n      warp_type ~ severity + noise_sd,\n      scales = \"free_x\",\n      labeller = cond_labeller\n    ) +\n    scale_fill_manual(values = mcols, labels = mlabs, guide = \"none\") +\n    scale_y_discrete(labels = mlabs) +\n    scale_x_continuous(trans = \"log2\",\n      breaks = c(0.125, 0.25, 0.5, 1, 2, 4, 8),\n      labels = c(\"1/8\", \"1/4\", \"1/2\", \"1\", \"2\", \"4\", \"8\")) +\n    labs(y = NULL, x = expression(\"Amplitude variance ratio (\" * log[2] * \" scale)\")) +\n    theme_benchmark()\n}\n```\n\n::: {.cell-output-display}\n![Amplitude variance ratio by method, stratified by warp type (rows) and severity × noise conditions (columns). DGPs with amplitude variation only (D05--D13). Dashed line at 1. Boxplots pool across DGPs within each warp type.](sim-report-main_files/figure-html/q4-amp-variance-ratio-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Compute AVR by method (pooled across amplitude DGPs)\navr_by_m <- dt[\n  amplitude != \"none\" & failure == FALSE & !is.na(amp_variance_ratio),\n  .(avr_med = median(amp_variance_ratio, na.rm = TRUE),\n    avr_q25 = quantile(amp_variance_ratio, 0.25, na.rm = TRUE),\n    avr_q75 = quantile(amp_variance_ratio, 0.75, na.rm = TRUE)),\n  by = method\n]\n\ncat(\"**Findings:**\\n\\n\")\n```\n\n**Findings:**\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(avr_by_m))) {\n  m <- avr_by_m$method[i]\n  med <- avr_by_m$avr_med[i]\n  q25 <- avr_by_m$avr_q25[i]\n  q75 <- avr_by_m$avr_q75[i]\n  direction <- if (med < 0.9) {\n    \"over-registration (absorbing amplitude into phase)\"\n  } else if (med > 1.1) {\n    \"under-registration or template bias inflating residuals\"\n  } else {\n    \"near-calibrated residual amplitude variance\"\n  }\n  cat(sprintf(\n    \"- **%s**: median AVR = %.2f [IQR: %.2f--%.2f], suggesting %s.\\n\",\n    mlabs[m], med, q25, q75, direction\n  ))\n}\n```\n\n- **Affine (S+S)**: median AVR = 1.68 [IQR: 1.26--2.67], suggesting under-registration or template bias inflating residuals.\n- **FDA (crit 1)**: median AVR = 1.61 [IQR: 0.83--3.54], suggesting under-registration or template bias inflating residuals.\n- **FDA (default)**: median AVR = 1.97 [IQR: 1.20--4.85], suggesting under-registration or template bias inflating residuals.\n- **Landmark (auto)**: median AVR = 5.19 [IQR: 2.61--6.96], suggesting under-registration or template bias inflating residuals.\n- **SRVF**: median AVR = 1.37 [IQR: 1.09--2.42], suggesting under-registration or template bias inflating residuals.\n\n```{.r .cell-code}\ncat(\"\\nNote: AVR > 1 can reflect either residual phase variation (under-registration) *or* template estimation error inflating residuals — these effects are confounded in this metric.\\n\")\n```\n\n\nNote: AVR > 1 can reflect either residual phase variation (under-registration) *or* template estimation error inflating residuals — these effects are confounded in this metric.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n\n## Template estimation (Q5) {#sec-q5}\n\n*Question: How well does each method estimate the template?*\n\n**Template MISE** measures $\\int_0^1 (\\hat{\\mu}(t) - \\mu(t))^2\\, dt$ where\n$\\hat{\\mu}$ is the method's estimated template and $\\mu$ the true template.\nThis conflates shape error with phase error: two templates differing only by\na warp are \"the same shape\" but have nonzero $L^2$ distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = template_mise, fill = method)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n  facet_grid(\n    template ~ severity + noise_sd,\n    scales = \"free_x\",\n    labeller = cond_labeller\n  ) +\n  scale_fill_manual(values = mcols, labels = mlabs, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  labs(y = NULL, x = \"Template MISE (log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Distribution of template MISE by method, stratified by template type (rows) and severity × noise (columns).](sim-report-main_files/figure-html/q5-template-1.png){width=960}\n:::\n:::\n\n\nTo address the phase-shape confound in $L^2$ template MISE, we also compute the\n**elastic (Fisher-Rao) amplitude distance** between estimated and true templates:\n$$d_a(\\hat\\mu, \\mu) = \\min_\\gamma \\| q_{\\hat\\mu} - (q_\\mu \\circ \\gamma)\\sqrt{\\gamma'} \\|_{L^2}, \\quad\nq_f(t) = \\text{sign}(f'(t))\\sqrt{|f'(t)|}$$\nwhere the minimization over reparameterizations $\\gamma$ is solved via dynamic programming\n(fdasrvf). This measures template *shape* distance invariant to reparameterization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (\"template_elastic_dist\" %in% names(dt)) {\n  ggplot(\n    dt[failure == FALSE & !is.na(template_elastic_dist)],\n    aes(y = method, x = template_elastic_dist, fill = method)\n  ) +\n    geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n    facet_grid(\n      template ~ severity + noise_sd,\n      scales = \"free_x\",\n      labeller = cond_labeller\n    ) +\n    scale_fill_manual(values = mcols, labels = mlabs, guide = \"none\") +\n    scale_y_discrete(labels = mlabs) +\n    scale_x_log10() +\n    labs(y = NULL, x = \"Elastic template distance (log scale)\") +\n    theme_benchmark()\n} else {\n  cat(\"*template_elastic_dist not available in current results — requires re-run with updated sim-run.R.*\")\n}\n```\n\n::: {.cell-output-display}\n![Distribution of elastic (SRSF) template distance by method, stratified by template type (rows) and severity × noise (columns). Invariant to phase shifts in the template.](sim-report-main_files/figure-html/q5-elastic-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Best method per template x severity x noise\nq5_best <- dt[failure == FALSE,\n  .(tmise = median(template_mise, na.rm = TRUE)),\n  by = .(method, template, severity, noise_sd)\n]\n\nhas_elastic <- \"template_elastic_dist\" %in% names(dt)\nif (has_elastic) {\n  q5_elastic <- dt[failure == FALSE & !is.na(template_elastic_dist),\n    .(edist = median(template_elastic_dist, na.rm = TRUE)),\n    by = .(method, template, severity, noise_sd)\n  ]\n}\n\ncat(\"**Findings (L2 MISE):**\\n\\n\")\n```\n\n**Findings (L2 MISE):**\n\n```{.r .cell-code}\nfor (tpl in unique(dt$template)) {\n  cat(sprintf(\"*%s template:*\\n\\n\", tpl))\n  for (s in levels(dt$severity)) {\n    for (ns in levels(dt$noise_sd)) {\n      sub <- q5_best[template == tpl & severity == s & noise_sd == ns]\n      best_m <- sub[which.min(tmise), method]\n      best_v <- sub[which.min(tmise), tmise]\n      cat(sprintf(\n        \"- sev=%s, noise=%s: **%s** (%.4f)\\n\",\n        s, ns, mlabs[best_m], best_v\n      ))\n    }\n  }\n  cat(\"\\n\")\n}\n```\n\n*harmonic template:*\n\n- sev=0.5, noise=0: **SRVF** (0.0028)\n- sev=0.5, noise=0.1: **Landmark (auto)** (0.0029)\n- sev=0.5, noise=0.3: **FDA (default)** (0.0052)\n- sev=1, noise=0: **SRVF** (0.0054)\n- sev=1, noise=0.1: **FDA (default)** (0.0259)\n- sev=1, noise=0.3: **FDA (default)** (0.0391)\n\n*wiggly template:*\n\n- sev=0.5, noise=0: **SRVF** (0.0091)\n- sev=0.5, noise=0.1: **SRVF** (0.0143)\n- sev=0.5, noise=0.3: **SRVF** (0.0622)\n- sev=1, noise=0: **SRVF** (0.0350)\n- sev=1, noise=0.1: **SRVF** (0.0525)\n- sev=1, noise=0.3: **SRVF** (0.3682)\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\nif (has_elastic) {\n  cat(\"**Findings (elastic distance):**\\n\\n\")\n  for (tpl in unique(dt$template)) {\n    cat(sprintf(\"*%s template:*\\n\\n\", tpl))\n    for (s in levels(dt$severity)) {\n      for (ns in levels(dt$noise_sd)) {\n        sub <- q5_elastic[template == tpl & severity == s & noise_sd == ns]\n        if (nrow(sub) == 0) next\n        best_m <- sub[which.min(edist), method]\n        best_v <- sub[which.min(edist), edist]\n        cat(sprintf(\n          \"- sev=%s, noise=%s: **%s** (%.4f)\\n\",\n          s, ns, mlabs[best_m], best_v\n        ))\n      }\n    }\n    cat(\"\\n\")\n  }\n}\n```\n\n**Findings (elastic distance):**\n\n*harmonic template:*\n\n- sev=0.5, noise=0: **SRVF** (0.1253)\n- sev=0.5, noise=0.1: **Landmark (auto)** (0.2419)\n- sev=0.5, noise=0.3: **Landmark (auto)** (0.7039)\n- sev=1, noise=0: **SRVF** (0.1433)\n- sev=1, noise=0.1: **FDA (crit 1)** (0.2927)\n- sev=1, noise=0.3: **Landmark (auto)** (0.8365)\n\n*wiggly template:*\n\n- sev=0.5, noise=0: **SRVF** (0.4280)\n- sev=0.5, noise=0.1: **SRVF** (0.6063)\n- sev=0.5, noise=0.3: **FDA (crit 1)** (1.3076)\n- sev=1, noise=0: **SRVF** (0.7016)\n- sev=1, noise=0.1: **SRVF** (0.8909)\n- sev=1, noise=0.3: **Affine (S+S)** (1.7142)\n\n```{.r .cell-code}\n# Worst method per template\ncat(\"**Template-specific patterns:**\\n\\n\")\n```\n\n**Template-specific patterns:**\n\n```{.r .cell-code}\nfor (tpl in unique(dt$template)) {\n  tpl_best <- q5_best[template == tpl, .(tmise = median(tmise)), by = method]\n  worst_m <- tpl_best[which.max(tmise), method]\n  best_m <- tpl_best[which.min(tmise), method]\n  cat(sprintf(\n    \"- *%s*: **%s** achieves the lowest median MISE; **%s** the highest.\\n\",\n    tpl, mlabs[best_m], mlabs[worst_m]\n  ))\n}\n```\n\n- *harmonic*: **FDA (default)** achieves the lowest median MISE; **SRVF** the highest.\n- *wiggly*: **SRVF** achieves the lowest median MISE; **Landmark (auto)** the highest.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"\\n**L² MISE vs elastic distance:**\\n\\n\")\n```\n\n\n**L² MISE vs elastic distance:**\n\n```{.r .cell-code}\ncat(\"Template MISE uses $L^2$ distance, which conflates shape error with phase error. The elastic (Fisher-Rao) amplitude distance is invariant to reparameterization and thus isolates *shape* quality.\\n\\n\")\n```\n\nTemplate MISE uses $L^2$ distance, which conflates shape error with phase error. The elastic (Fisher-Rao) amplitude distance is invariant to reparameterization and thus isolates *shape* quality.\n\n```{.r .cell-code}\nif (has_elastic) {\n  # Rank correlation between the two metrics\n  agg_both <- dt[failure == FALSE & !is.na(template_elastic_dist) & !is.na(template_mise),\n    .(edist = median(template_elastic_dist), tmise = median(template_mise)),\n    by = .(dgp, severity, noise_sd, method)]\n  agg_both[, rank_e := frank(edist), by = .(dgp, severity, noise_sd)]\n  agg_both[, rank_m := frank(tmise), by = .(dgp, severity, noise_sd)]\n  rho <- round(cor(agg_both$rank_e, agg_both$rank_m, method = \"spearman\"), 2)\n\n  # Best-method disagreement\n  best_e <- agg_both[, .SD[which.min(edist)], by = .(dgp, severity, noise_sd)]\n  best_m <- agg_both[, .SD[which.min(tmise)], by = .(dgp, severity, noise_sd)]\n  merged <- merge(\n    best_e[, .(dgp, severity, noise_sd, best_elastic = method)],\n    best_m[, .(dgp, severity, noise_sd, best_mise = method)]\n  )\n  n_disagree <- sum(merged$best_elastic != merged$best_mise)\n  n_total <- nrow(merged)\n\n  # Win rates by elastic distance\n  agg_both[, rank_e2 := frank(edist), by = .(dgp, severity, noise_sd)]\n  wr <- agg_both[, .(win_pct = round(100 * mean(rank_e2 == 1), 1)), by = method][order(-win_pct)]\n\n  # Noise sensitivity ratio (noise=0.3 / noise=0), conditioned on template\n  noise_sens <- dt[\n    failure == FALSE & !is.na(template_elastic_dist) & noise_sd %in% c(\"0\", \"0.3\"),\n    .(edist = median(template_elastic_dist)),\n    by = .(method, template, noise_sd)\n  ]\n  wide <- dcast(noise_sens, method + template ~ noise_sd, value.var = \"edist\")\n  setnames(wide, c(\"0\", \"0.3\"), c(\"e0\", \"e03\"))\n  wide[, ratio := round(e03 / e0, 2)]\n  # Summarize across templates (median of template-specific ratios)\n  wide_pooled <- wide[, .(ratio = round(median(ratio), 1)), by = method]\n\n  cat(sprintf(\n    \"The two metrics agree moderately (Spearman $\\\\rho$ = %s across cell-level method rankings) but disagree on the best method in **%d of %d** conditions (%.0f%%). Key differences:\\n\\n\",\n    rho, n_disagree, n_total, 100 * n_disagree / n_total\n  ))\n  cat(sprintf(\n    \"- **%s** wins most often on elastic distance (%s%% of conditions), suggesting it recovers template *shape* well even when its $L^2$ MISE is mediocre (phase shifts inflate MISE but not elastic distance).\\n\",\n    mlabs[wr$method[1]], wr$win_pct[1]\n  ))\n  cat(sprintf(\n    \"- **%s** rarely wins on elastic distance (%s%%), despite reasonable $L^2$ MISE — its templates have good pointwise fit but suboptimal shape recovery.\\n\",\n    mlabs[wr$method[nrow(wr)]], wr$win_pct[nrow(wr)]\n  ))\n\n  # Noise sensitivity (template-conditioned to avoid pooling artifacts)\n  srvf_ratio <- wide_pooled[method == \"srvf\", ratio]\n  most_robust <- wide_pooled[which.min(ratio)]\n  cat(sprintf(\n    \"- **Noise sensitivity** (median ratio noise=0.3 / noise=0, conditioned on template): SRVF degrades %.1f×, while %s is most robust (%.1f×).\\n\",\n    srvf_ratio, mlabs[most_robust$method], most_robust$ratio\n  ))\n  # Affine: show per-template ratios since pooling can mask heterogeneity\n  affine_by_tpl <- wide[method == \"affine_ss\"]\n  if (nrow(affine_by_tpl) > 0) {\n    affine_txt <- paste(sprintf(\"%s: %.1f×\", affine_by_tpl$template, affine_by_tpl$ratio),\n      collapse = \", \")\n    cat(sprintf(\n      \"- Affine (S+S) noise sensitivity varies by template (%s) — the pooled ratio masks heterogeneity. Elastic distance is always high (median %.2f–%.2f), indicating consistent template shape distortion.\\n\",\n      affine_txt,\n      min(noise_sens[method == \"affine_ss\", edist]),\n      max(noise_sens[method == \"affine_ss\", edist])\n    ))\n  }\n} else {\n  cat(\"*Elastic distance not available in current results.*\\n\")\n}\n```\n\nThe two metrics agree moderately (Spearman $\\rho$ = 0.6 across cell-level method rankings) but disagree on the best method in **34 of 90** conditions (38%). Key differences:\n\n- **SRVF** wins most often on elastic distance (38.9% of conditions), suggesting it recovers template *shape* well even when its $L^2$ MISE is mediocre (phase shifts inflate MISE but not elastic distance).\n- **FDA (default)** rarely wins on elastic distance (6.7%), despite reasonable $L^2$ MISE — its templates have good pointwise fit but suboptimal shape recovery.\n- **Noise sensitivity** (median ratio noise=0.3 / noise=0, conditioned on template): SRVF degrades 8.7×, while Affine (S+S) is most robust (1.5×).\n- Affine (S+S) noise sensitivity varies by template (harmonic: 1.9×, wiggly: 1.1×) — the pooled ratio masks heterogeneity. Elastic distance is always high (median 0.44–1.49), indicating consistent template shape distortion.\n\n```{.r .cell-code}\ncat(\"\\n\\n\")\n```\n\n# Sensitivity & Variance Decomposition (Q6) {#sec-sensitivity}\n\n*Question: Which factors most influence each metric, and how do noise and severity interact with method and DGP characteristics?*\n\n## Median warp MISE across all conditions {#sec-q6-overview}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagg_q6 <- dt[failure == FALSE,\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(dgp, method, warp_type, severity, noise_sd)]\n\nggplot(agg_q6, aes(x = method, y = mise, color = method)) +\n  geom_jitter(width = 0.15, size = 1.5, alpha = 0.6) +\n  stat_summary(fun = median, geom = \"crossbar\", width = 0.4,\n    color = \"black\", linewidth = 0.4) +\n  facet_grid(\n    warp_type ~ severity + noise_sd,\n    scales = \"free_y\",\n    labeller = cond_labeller\n  ) +\n  scale_color_manual(values = mcols, labels = mlabs, guide = \"none\") +\n  scale_x_discrete(labels = mlabs) +\n  scale_y_log10() +\n  labs(x = NULL, y = \"Median warp MISE (log scale)\") +\n  theme_benchmark() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![Median warp MISE by method across all severity × noise conditions, stratified by warp type (rows). Each dot = one DGP; crossbar = median across DGPs.](sim-report-main_files/figure-html/q6-combined-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Degradation ratios — noise\nratios <- degradation_ratios(dt)\nnoise_rat <- ratios$noise[is.finite(noise_ratio)]\nnoise_rat <- merge(noise_rat, dgp_factors(), by = \"dgp\")\n\ncat(\"**Noise × method × warp type interaction:**\\n\\n\")\n```\n\n**Noise × method × warp type interaction:**\n\n```{.r .cell-code}\nfor (wt in c(\"simple\", \"complex\", \"affine\")) {\n  cat(sprintf(\"*%s warps:*\\n\\n\", wt))\n  for (nl in sort(unique(as.character(noise_rat$noise_sd)))) {\n    sub <- noise_rat[warp_type == wt & noise_sd == nl & severity == \"0.5\",\n      .(ratio = median(noise_ratio, na.rm = TRUE)), by = method][order(-ratio)]\n    most <- sub[1]\n    least <- sub[.N]\n    cat(sprintf(\n      \"- noise=%s: strongest degradation for %s (%.1f$\\\\times$), weakest for %s (%.2f$\\\\times$)\\n\",\n      nl, mlabs[most$method], most$ratio, mlabs[least$method], least$ratio\n    ))\n  }\n  cat(\"\\n\")\n}\n```\n\n*simple warps:*\n\n- noise=0.1: strongest degradation for SRVF (11.7$\\times$), weakest for FDA (default) (0.97$\\times$)\n- noise=0.3: strongest degradation for SRVF (106.8$\\times$), weakest for FDA (crit 1) (0.78$\\times$)\n\n*complex warps:*\n\n- noise=0.1: strongest degradation for SRVF (23.2$\\times$), weakest for Landmark (auto) (0.92$\\times$)\n- noise=0.3: strongest degradation for SRVF (125.2$\\times$), weakest for FDA (default) (0.87$\\times$)\n\n*affine warps:*\n\n- noise=0.1: strongest degradation for SRVF (1.4$\\times$), weakest for Affine (S+S) (0.97$\\times$)\n- noise=0.3: strongest degradation for SRVF (4.1$\\times$), weakest for FDA (crit 1) (0.94$\\times$)\n\n```{.r .cell-code}\n# SRVF noise note\ncat(\"SRVF operates on SRSFs (derivatives), amplifying high-frequency noise — this is the dominant noise sensitivity pattern. Study B (penalization) will test regularization.\\n\\n\")\n```\n\nSRVF operates on SRSFs (derivatives), amplifying high-frequency noise — this is the dominant noise sensitivity pattern. Study B (penalization) will test regularization.\n\n```{.r .cell-code}\n# Explain ratio < 1 phenomenon\nany_below_1 <- noise_rat[severity == \"0.5\", .(ratio = median(noise_ratio, na.rm = TRUE)), by = method][ratio < 1]\nif (nrow(any_below_1) > 0) {\n  cat(sprintf(\n    \"**Note on degradation ratios below 1**: %s show median noise ratio $< 1$ in some conditions, meaning warp MISE *decreases* with added noise. This likely reflects an implicit regularization effect — noise shrinks the cross-covariance estimates, producing smoother (less aggressive) warps that happen to be closer to the truth when the clean-data algorithm slightly over-registers. This should not be interpreted as 'noise helps registration'.\\n\\n\",\n    paste(mlabs[any_below_1$method], collapse = \" and \")\n  ))\n}\n```\n\n**Note on degradation ratios below 1**: FDA (default) and FDA (crit 1) show median noise ratio $< 1$ in some conditions, meaning warp MISE *decreases* with added noise. This likely reflects an implicit regularization effect — noise shrinks the cross-covariance estimates, producing smoother (less aggressive) warps that happen to be closer to the truth when the clean-data algorithm slightly over-registers. This should not be interpreted as 'noise helps registration'.\n\n```{.r .cell-code}\n# Severity\nsev_rat <- ratios$severity[is.finite(severity_ratio)]\nsev_rat <- merge(sev_rat, dgp_factors(), by = \"dgp\")\nsev_agg <- sev_rat[, .(ratio = median(severity_ratio, na.rm = TRUE)),\n  by = .(method, warp_type)][order(warp_type, -ratio)]\ncat(\"**Severity effect** (pooled over noise):\\n\\n\")\n```\n\n**Severity effect** (pooled over noise):\n\n```{.r .cell-code}\nfor (wt in c(\"simple\", \"complex\", \"affine\")) {\n  sub <- sev_agg[warp_type == wt]\n  most <- sub[1]\n  least <- sub[.N]\n  cat(sprintf(\n    \"- *%s*: strongest for %s (%.1f$\\\\times$), weakest for %s (%.1f$\\\\times$)\\n\",\n    wt, mlabs[most$method], most$ratio, mlabs[least$method], least$ratio\n  ))\n}\n```\n\n- *simple*: strongest for Affine (S+S) (4.9$\\times$), weakest for FDA (crit 1) (2.9$\\times$)\n- *complex*: strongest for SRVF (7.1$\\times$), weakest for FDA (default) (3.1$\\times$)\n- *affine*: strongest for Landmark (auto) (5.5$\\times$), weakest for SRVF (2.7$\\times$)\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n## Method × noise interaction {#sec-method-noise}\n\nThe most actionable Study A finding is the interaction between method and noise level.\nThis plot directly shows how each method's performance changes with noise, stratified\nby warp type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmn_agg <- dt[failure == FALSE & severity == \"1\",\n  .(\n    mise = median(warp_mise, na.rm = TRUE),\n    q25 = quantile(warp_mise, 0.25, na.rm = TRUE),\n    q75 = quantile(warp_mise, 0.75, na.rm = TRUE)\n  ),\n  by = .(method, warp_type, noise_sd)]\n\nggplot(mn_agg, aes(x = noise_sd, y = mise, color = method, group = method)) +\n  geom_line(linewidth = 0.8) +\n  geom_point(size = 2.5) +\n  geom_errorbar(aes(ymin = q25, ymax = q75), width = 0.08, alpha = 0.35) +\n  facet_wrap(~ warp_type, scales = \"free_y\") +\n  scale_color_manual(values = mcols, labels = mlabs) +\n  scale_y_log10() +\n  labs(x = \"Noise level\", y = \"Median warp MISE (log scale)\", color = \"Method\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Method × noise interaction for warp MISE (severity=1.0). Points show medians and vertical bars show IQRs. Lines connect noise levels within each method. Diverging lines indicate differential noise sensitivity.](sim-report-main_files/figure-html/method-noise-interaction-1.png){width=960}\n:::\n:::\n\n\n\n```{.r .cell-code}\n# Check for rank reversals between noise=0 and highest noise\nmn_ranks <- mn_agg[, .(best = method[which.min(mise)]), by = .(warp_type, noise_sd)]\nmn_wide <- dcast(mn_ranks, warp_type ~ noise_sd, value.var = \"best\")\nhighest_noise_col <- names(mn_wide)[ncol(mn_wide)]\n\ncat(\"**Method × noise interaction:**\\n\\n\")\n```\n\n**Method × noise interaction:**\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(mn_wide))) {\n  wt <- mn_wide$warp_type[i]\n  clean_best <- mlabs[mn_wide[[\"0\"]][i]]\n  noisy_best <- mlabs[mn_wide[[highest_noise_col]][i]]\n  if (mn_wide[[\"0\"]][i] == mn_wide[[highest_noise_col]][i]) {\n    cat(sprintf(\"- **%s** warps: %s holds rank 1 from noise=0 to noise=%s.\\n\",\n      wt, clean_best, highest_noise_col))\n  } else {\n    cat(sprintf(\"- **%s** warps: **rank reversal** — %s best at noise=0, %s best at noise=%s.\\n\",\n      wt, clean_best, noisy_best, highest_noise_col))\n  }\n}\n```\n\n- **affine** warps: Affine (S+S) holds rank 1 from noise=0 to noise=0.3.\n- **simple** warps: **rank reversal** — SRVF best at noise=0, FDA (crit 1) best at noise=0.3.\n- **complex** warps: **rank reversal** — SRVF best at noise=0, FDA (default) best at noise=0.3.\n\n```{.r .cell-code}\ncat(\"\\n\")\n```\n\n## ANOVA variance decomposition {#sec-anova}\n\nFor each metric, we fit a factorial ANOVA with all main effects and 2nd-order\ninteractions of the design factors (method, template, warp type, amplitude,\nseverity, noise) and report $\\eta^2 = \\text{SS}_\\text{term} / \\text{SS}_\\text{total}$\nfor the 10 most important terms. We use **Type II** sums of squares\n(`car::Anova(type = \"II\")`) because the DGP design is not full factorial\n(15 of 24 cells), making Type I SS order-dependent. Type II SS tests each\nterm after all other terms of equal or lower order, giving stable $\\eta^2$\nregardless of factor ordering. Metrics that are plotted on a log scale\n(MISE, ratios, runtime) are log-transformed before fitting to match the\nanalysis scale and stabilize variance.\n\n\n```{.r .cell-code}\n#' Compute eta-squared from Type II ANOVA for a given metric\n#' Returns top-k terms by eta-squared\n#' Uses car::Anova(type = \"II\") for stable SS in non-full-factorial design.\n#' Metrics plotted on log scale are log-transformed before ANOVA.\ncompute_anova_eta2 <- function(dt, metric, use_log = FALSE, k = 10) {\n  d <- dt[failure == FALSE & !is.na(get(metric))]\n  if (use_log) {\n    d <- d[get(metric) > 0]\n    d[, (metric) := log(get(metric))]\n  }\n  for (v in c(\"method\", \"template\", \"warp_type\", \"amplitude\", \"severity\", \"noise_sd\")) {\n    d[[v]] <- factor(d[[v]])\n  }\n  fml <- as.formula(paste0(\n    metric,\n    \" ~ (method + template + warp_type + amplitude + severity + noise_sd)^2\"\n  ))\n  fit <- lm(fml, data = d)\n  a2 <- car::Anova(fit, type = \"II\")\n  ss_df <- data.table(\n    term = rownames(a2),\n    ss = a2$`Sum Sq`,\n    df = a2$Df,\n    f = a2$`F value`,\n    p = a2$`Pr(>F)`\n  )\n  ss_df <- ss_df[term != \"Residuals\"]\n  ss_total <- sum(ss_df$ss, na.rm = TRUE) + a2[\"Residuals\", \"Sum Sq\"]\n  ss_df[, eta2 := ss / ss_total]\n  ss_df[order(-eta2)][seq_len(min(k, .N))]\n}\n\n# Metrics to analyze — with log-scale flag matching plot scales\nmetrics_for_anova <- list(\n  list(metric = \"warp_mise\",                  label = \"Warp MISE\",                log = TRUE),\n  list(metric = \"alignment_error\",            label = \"Alignment error\",           log = TRUE),\n  list(metric = \"template_mise\",              label = \"Template MISE\",             log = TRUE),\n  list(metric = \"alignment_cc\",               label = \"Alignment CC\",              log = FALSE),\n  list(metric = \"registration_ratio_median\",  label = \"Registration ratio\",        log = TRUE),\n  list(metric = \"amp_variance_ratio\",         label = \"Amplitude variance ratio\",  log = TRUE),\n  list(metric = \"warp_slope_ratio_median\",    label = \"Warp slope ratio\",          log = TRUE),\n  list(metric = \"time_per_curve\",             label = \"Time per curve\",            log = TRUE)\n)\n\nfor (spec in metrics_for_anova) {\n  metric <- spec$metric\n  label <- spec$label\n  use_log <- spec$log\n\n  # Skip if metric not in data or all NA\n  if (!(metric %in% names(dt))) next\n  if (all(is.na(dt[[metric]]))) next\n\n  top <- tryCatch(\n    compute_anova_eta2(dt, metric, use_log = use_log),\n    error = function(e) NULL\n  )\n  if (is.null(top) || nrow(top) == 0) next\n\n  scale_note <- if (use_log) \" (log scale)\" else \"\"\n  cat(sprintf(\"\\n### %s%s\\n\\n\", label, scale_note))\n  top[, eta2_pct := sprintf(\"%.1f%%\", 100 * eta2)]\n  top[, stars := ifelse(is.na(p), \"\",\n    ifelse(p < 0.001, \"***\",\n      ifelse(p < 0.01, \"**\",\n        ifelse(p < 0.05, \"*\", \"\"))))]\n  print(knitr::kable(\n    top[, .(Term = term, df, `eta^2` = eta2_pct, `F` = round(f, 1), Sig = stars)],\n    caption = sprintf(\"Top 10 terms by eta-squared for %s%s.\", label, scale_note)\n  ))\n  cat(\"\\n\")\n\n  # Brief data-driven summary\n  top1 <- top$term[1]\n  top1_eta2 <- top$eta2[1]\n  top3 <- top$term[1:min(3, nrow(top))]\n  cat(sprintf(\n    \"The dominant source of variation is **%s** ($\\\\eta^2$ = %.1f%%). The top 3 terms (%s) together explain %.1f%% of total variance.\\n\\n\",\n    top1, 100 * top1_eta2,\n    paste(top3, collapse = \", \"),\n    100 * sum(top$eta2[1:min(3, nrow(top))])\n  ))\n}\n```\n\n\n### Warp MISE (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Warp MISE (log scale).\n\n|Term             | df|eta^2 |     F|Sig |\n|:----------------|--:|:-----|-----:|:---|\n|method           |  4|22.1% | 13313|*** |\n|severity         |  1|14.8% | 35744|*** |\n|method:template  |  4|10.8% |  6519|*** |\n|template         |  1|7.5%  | 18128|*** |\n|method:noise_sd  |  8|7.4%  |  2224|*** |\n|method:warp_type |  8|5.6%  |  1686|*** |\n|warp_type        |  2|4.7%  |  5708|*** |\n|amplitude        |  3|2.7%  |  2149|*** |\n|noise_sd         |  2|2.4%  |  2848|*** |\n|method:amplitude | 12|1.0%  |   207|*** |\n\nThe dominant source of variation is **method** ($\\eta^2$ = 22.1%). The top 3 terms (method, severity, method:template) together explain 47.8% of total variance.\n\n\n### Alignment error (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Alignment error (log scale).\n\n|Term             | df|eta^2 |     F|Sig |\n|:----------------|--:|:-----|-----:|:---|\n|template         |  1|21.7% | 52482|*** |\n|method           |  4|14.2% |  8594|*** |\n|severity         |  1|9.8%  | 23828|*** |\n|method:noise_sd  |  8|7.2%  |  2182|*** |\n|noise_sd         |  2|7.2%  |  8725|*** |\n|method:template  |  4|7.1%  |  4301|*** |\n|method:warp_type |  8|4.4%  |  1334|*** |\n|amplitude        |  3|2.6%  |  2064|*** |\n|warp_type        |  2|1.9%  |  2308|*** |\n|method:amplitude | 12|1.3%  |   267|*** |\n\nThe dominant source of variation is **template** ($\\eta^2$ = 21.7%). The top 3 terms (template, method, severity) together explain 45.7% of total variance.\n\n\n### Template MISE (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Template MISE (log scale).\n\n|Term              | df|eta^2 |     F|Sig |\n|:-----------------|--:|:-----|-----:|:---|\n|template          |  1|36.7% | 88025|*** |\n|severity          |  1|12.9% | 30893|*** |\n|method:template   |  4|10.9% |  6533|*** |\n|method:noise_sd   |  8|6.6%  |  1980|*** |\n|method:warp_type  |  8|4.7%  |  1403|*** |\n|warp_type         |  2|2.1%  |  2518|*** |\n|noise_sd          |  2|2.0%  |  2380|*** |\n|method            |  4|1.4%  |   827|*** |\n|amplitude         |  3|1.0%  |   813|*** |\n|template:severity |  1|0.8%  |  2035|*** |\n\nThe dominant source of variation is **template** ($\\eta^2$ = 36.7%). The top 3 terms (template, severity, method:template) together explain 60.5% of total variance.\n\n\n### Alignment CC\n\n\n\nTable: Top 10 terms by eta-squared for Alignment CC.\n\n|Term               | df|eta^2 |     F|Sig |\n|:------------------|--:|:-----|-----:|:---|\n|template           |  1|37.1% | 84516|*** |\n|method             |  4|11.6% |  6598|*** |\n|method:template    |  4|11.1% |  6340|*** |\n|severity           |  1|9.3%  | 21194|*** |\n|template:severity  |  1|3.4%  |  7823|*** |\n|warp_type          |  2|2.0%  |  2288|*** |\n|method:noise_sd    |  8|1.6%  |   460|*** |\n|template:warp_type |  2|1.5%  |  1681|*** |\n|noise_sd           |  2|0.9%  |  1026|*** |\n|method:warp_type   |  8|0.6%  |   182|*** |\n\nThe dominant source of variation is **template** ($\\eta^2$ = 37.1%). The top 3 terms (template, method, method:template) together explain 59.8% of total variance.\n\n\n### Registration ratio (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Registration ratio (log scale).\n\n|Term             | df|eta^2 |     F|Sig |\n|:----------------|--:|:-----|-----:|:---|\n|method           |  4|41.7% | 17197|*** |\n|method:severity  |  4|10.8% |  4448|*** |\n|severity         |  1|2.9%  |  4841|*** |\n|method:warp_type |  8|2.8%  |   577|*** |\n|warp_type        |  2|2.6%  |  2173|*** |\n|method:noise_sd  |  8|2.5%  |   517|*** |\n|noise_sd         |  2|2.3%  |  1922|*** |\n|template         |  1|2.1%  |  3414|*** |\n|method:template  |  4|1.8%  |   731|*** |\n|amplitude        |  3|0.7%  |   362|*** |\n\nThe dominant source of variation is **method** ($\\eta^2$ = 41.7%). The top 3 terms (method, method:severity, severity) together explain 55.4% of total variance.\n\n\n### Amplitude variance ratio (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Amplitude variance ratio (log scale).\n\n|Term               | df|eta^2 |     F|Sig |\n|:------------------|--:|:-----|-----:|:---|\n|template           |  1|27.5% | 59272|*** |\n|method             |  4|21.6% | 11625|*** |\n|method:template    |  4|15.3% |  8247|*** |\n|noise_sd           |  2|8.5%  |  9157|*** |\n|severity           |  1|7.1%  | 15262|*** |\n|method:noise_sd    |  8|2.7%  |   736|*** |\n|warp_type          |  2|1.5%  |  1621|*** |\n|template:noise_sd  |  2|1.5%  |  1594|*** |\n|template:warp_type |  2|0.7%  |   725|*** |\n|method:warp_type   |  8|0.4%  |   121|*** |\n\nThe dominant source of variation is **template** ($\\eta^2$ = 27.5%). The top 3 terms (template, method, method:template) together explain 64.5% of total variance.\n\n\n### Warp slope ratio (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Warp slope ratio (log scale).\n\n|Term               | df|eta^2 |        F|Sig |\n|:------------------|--:|:-----|--------:|:---|\n|method             |  4|97.8% | 481905.0|*** |\n|severity           |  1|0.1%  |   1321.9|*** |\n|warp_type          |  1|0.1%  |   1086.7|*** |\n|method:template    |  4|0.1%  |    262.3|*** |\n|method:amplitude   | 12|0.0%  |     54.3|*** |\n|method:warp_type   |  4|0.0%  |    155.7|*** |\n|method:noise_sd    |  8|0.0%  |     67.9|*** |\n|method:severity    |  4|0.0%  |     89.0|*** |\n|warp_type:noise_sd |  2|0.0%  |    130.2|*** |\n|template:severity  |  1|0.0%  |    251.7|*** |\n\nThe dominant source of variation is **method** ($\\eta^2$ = 97.8%). The top 3 terms (method, severity, warp_type) together explain 97.9% of total variance.\n\n\n### Time per curve (log scale)\n\n\n\nTable: Top 10 terms by eta-squared for Time per curve (log scale).\n\n|Term              | df|eta^2 |      F|Sig |\n|:-----------------|--:|:-----|------:|:---|\n|method            |  4|95.6% | 303190|*** |\n|noise_sd          |  2|0.1%  |    866|*** |\n|method:warp_type  |  8|0.1%  |    216|*** |\n|method:amplitude  | 12|0.1%  |    129|*** |\n|method:noise_sd   |  8|0.1%  |    178|*** |\n|method:template   |  4|0.1%  |    287|*** |\n|method:severity   |  4|0.1%  |    285|*** |\n|severity:noise_sd |  2|0.1%  |    459|*** |\n|template          |  1|0.0%  |    399|*** |\n|template:noise_sd |  2|0.0%  |    172|*** |\n\nThe dominant source of variation is **method** ($\\eta^2$ = 95.6%). The top 3 terms (method, noise_sd, method:warp_type) together explain 95.8% of total variance.\n\n# Practical (Q7) {#sec-practical}\n\n## Runtime {#sec-runtime}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  dt[failure == FALSE],\n  aes(y = method, x = time_per_curve, fill = method)\n) +\n  geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +\n  scale_fill_manual(values = mcols, labels = mlabs, guide = \"none\") +\n  scale_y_discrete(labels = mlabs) +\n  scale_x_log10() +\n  labs(y = NULL, x = \"Time per curve (seconds, log scale)\") +\n  theme_benchmark()\n```\n\n::: {.cell-output-display}\n![Distribution of time per curve (seconds) by method across all conditions. Log10 scale. Boxplots show all non-failed runs.](sim-report-main_files/figure-html/q7-runtime-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_tbl <- dt[failure == FALSE, .(\n  median = round(median(time_per_curve, na.rm = TRUE), 3),\n  q25 = round(quantile(time_per_curve, 0.25, na.rm = TRUE), 3),\n  q75 = round(quantile(time_per_curve, 0.75, na.rm = TRUE), 3)\n), by = method][order(-median)]\n\nknitr::kable(time_tbl,\n  col.names = c(\"Method\", \"Median (s)\", \"Q25 (s)\", \"Q75 (s)\"),\n  caption = \"Time per curve (seconds) across all conditions.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Time per curve (seconds) across all conditions.\n\n|Method        | Median (s)| Q25 (s)| Q75 (s)|\n|:-------------|----------:|-------:|-------:|\n|fda_crit1     |      0.200|   0.165|   0.264|\n|srvf          |      0.180|   0.179|   0.181|\n|fda_default   |      0.118|   0.105|   0.162|\n|affine_ss     |      0.094|   0.070|   0.127|\n|landmark_auto |      0.003|   0.003|   0.004|\n\n\n:::\n:::\n\n\n\n```{.r .cell-code}\nrt <- dt[failure == FALSE, .(\n  med = median(time_per_curve, na.rm = TRUE)\n), by = method][order(-med)]\n\ncat(\"**Runtime findings:**\\n\\n\")\n```\n\n**Runtime findings:**\n\n```{.r .cell-code}\nfor (i in seq_len(nrow(rt))) {\n  cat(sprintf(\"- **%s**: %.3f s/curve\\n\", mlabs[rt$method[i]], rt$med[i]))\n}\n```\n\n- **FDA (crit 1)**: 0.200 s/curve\n- **SRVF**: 0.180 s/curve\n- **FDA (default)**: 0.118 s/curve\n- **Affine (S+S)**: 0.094 s/curve\n- **Landmark (auto)**: 0.003 s/curve\n\n```{.r .cell-code}\nfastest <- rt[.N]\nslowest <- rt[1]\nratio <- slowest$med / fastest$med\ncat(sprintf(\n  \"\\n%s is %.0f$\\\\times$ slower than %s (the fastest).\\n\\n\",\n  mlabs[slowest$method], ratio, mlabs[fastest$method]\n))\n```\n\n\nFDA (crit 1) is 58$\\times$ slower than Landmark (auto) (the fastest).\n\n## Failures {#sec-failures}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfail_tbl <- failure_summary(dt)\nfail_tbl[, rate := round(rate, 3)]\nknitr::kable(\n  fail_tbl[order(method, warp_type)],\n  col.names = c(\"Method\", \"Warp type\", \"N total\", \"N failed\", \"Rate\"),\n  caption = \"Failure rates by method and warp type.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Failure rates by method and warp type.\n\n|Method        |Warp type | N total| N failed|  Rate|\n|:-------------|:---------|-------:|--------:|-----:|\n|srvf          |affine    |    1800|        0| 0.000|\n|srvf          |simple    |    3600|        0| 0.000|\n|srvf          |complex   |    3600|        0| 0.000|\n|fda_default   |affine    |    1800|        0| 0.000|\n|fda_default   |simple    |    3600|        0| 0.000|\n|fda_default   |complex   |    3600|        0| 0.000|\n|fda_crit1     |affine    |    1800|        0| 0.000|\n|fda_crit1     |simple    |    3600|        0| 0.000|\n|fda_crit1     |complex   |    3600|        0| 0.000|\n|affine_ss     |affine    |    1800|        0| 0.000|\n|affine_ss     |simple    |    3600|        0| 0.000|\n|affine_ss     |complex   |    3600|        0| 0.000|\n|landmark_auto |affine    |    1800|        0| 0.000|\n|landmark_auto |simple    |    3600|        8| 0.002|\n|landmark_auto |complex   |    3600|        2| 0.001|\n\n\n:::\n:::\n\n\n\n```{.r .cell-code}\nerr <- dt[failure == TRUE & nchar(error_msg) > 0]\nerr[, error_class := fcase(\n  grepl(\"monotonic\", error_msg), \"Non-monotonic warp\",\n  grepl(\"duplicated values\", error_msg), \"Duplicated arg values in warped curves\",\n  grepl(\"computationally singular\", error_msg), \"Singular linear system\",\n  grepl(\"missing value where TRUE/FALSE\", error_msg), \"NA in logical comparison\",\n  default = \"Other\"\n)]\n\ncat(\"**Error analysis:**\\n\\n\")\n```\n\n**Error analysis:**\n\n```{.r .cell-code}\ncat(sprintf(\"Total failures: %d out of %d runs (%.2f%%).\\n\\n\",\n  sum(dt$failure), nrow(dt), 100 * mean(dt$failure)))\n```\n\nTotal failures: 10 out of 45000 runs (0.02%).\n\n```{.r .cell-code}\nif (sum(dt$failure) == 0) {\n  cat(\"No failures — all runs completed successfully.\\n\\n\")\n} else {\n  # Failures by method\n  fail_by_method <- dt[failure == TRUE, .N, by = method][order(-N)]\n  cat(\"Failures by method:\\n\\n\")\n  for (i in seq_len(nrow(fail_by_method))) {\n    m <- fail_by_method$method[i]\n    n <- fail_by_method$N[i]\n    n_total <- dt[method == m, .N]\n    cat(sprintf(\"- **%s**: %d failures (%.2f%%)\\n\",\n      mlabs[m], n, 100 * n / n_total))\n  }\n  cat(\"\\n\")\n\n  # Error classes\n  if (nrow(err) > 0) {\n    err_summary <- err[, .N, by = error_class][order(-N)]\n    cat(\"Error types:\\n\\n\")\n    for (i in seq_len(nrow(err_summary))) {\n      cat(sprintf(\"- **%s** (%d cases)\\n\",\n        err_summary$error_class[i], err_summary$N[i]))\n    }\n    cat(\"\\n\")\n\n    # DGP concentration\n    fail_by_dgp <- err[, .N, by = dgp][order(-N)]\n    if (nrow(fail_by_dgp) <= 5) {\n      cat(sprintf(\"Failures concentrated in %d DGP(s): %s.\\n\\n\",\n        nrow(fail_by_dgp),\n        paste(sprintf(\"%s (%d)\", fail_by_dgp$dgp, fail_by_dgp$N),\n          collapse = \", \")))\n    }\n  }\n}\n```\n\nFailures by method:\n\n- **Landmark (auto)**: 10 failures (0.11%)\n\nError types:\n\n- **Non-monotonic warp** (10 cases)\n\nFailures concentrated in 4 DGP(s): D09 (5), D01 (3), D02 (1), D10 (1).\n\n# Data Completeness {#sec-completeness}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomp <- dt[, .N, by = .(dgp, method)]\ncomp_wide <- dcast(comp, dgp ~ method, value.var = \"N\")\nknitr::kable(comp_wide,\n  caption = \"Number of runs per DGP x method (target: 600 = 2 severity x 3 noise x 100 reps). Missing cells indicate batches that did not complete on the cluster.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Number of runs per DGP x method (target: 600 = 2 severity x 3 noise x 100 reps). Missing cells indicate batches that did not complete on the cluster.\n\n|dgp | srvf| fda_default| fda_crit1| affine_ss| landmark_auto|\n|:---|----:|-----------:|---------:|---------:|-------------:|\n|D01 |  600|         600|       600|       600|           600|\n|D02 |  600|         600|       600|       600|           600|\n|D03 |  600|         600|       600|       600|           600|\n|D04 |  600|         600|       600|       600|           600|\n|D05 |  600|         600|       600|       600|           600|\n|D06 |  600|         600|       600|       600|           600|\n|D07 |  600|         600|       600|       600|           600|\n|D08 |  600|         600|       600|       600|           600|\n|D09 |  600|         600|       600|       600|           600|\n|D10 |  600|         600|       600|       600|           600|\n|D11 |  600|         600|       600|       600|           600|\n|D12 |  600|         600|       600|       600|           600|\n|D13 |  600|         600|       600|       600|           600|\n|D14 |  600|         600|       600|       600|           600|\n|D15 |  600|         600|       600|       600|           600|\n\n\n:::\n:::\n\n\n\n```{.r .cell-code}\nexpected <- CJ(\n  dgp = levels(dt$dgp),\n  method = levels(dt$method)\n)\nactual <- unique(dt[, .(dgp, method)])\nmissing <- expected[!actual, on = .(dgp, method)]\nif (nrow(missing) > 0) {\n  cat(\"**Missing DGP x method combinations** (\", nrow(missing),\n    \" batches still running on LRZ):\\n\\n\", sep = \"\")\n  for (i in seq_len(nrow(missing))) {\n    cat(sprintf(\"- %s / %s\\n\", missing$dgp[i], missing$method[i]))\n  }\n} else {\n  cat(\"All DGP x method combinations present.\\n\")\n}\n```\n\nAll DGP x method combinations present.\n\n# Summary {#sec-summary}\n\n\n```{.r .cell-code}\ncat(\"## Key findings\\n\\n\")\n```\n\n## Key findings\n\n```{.r .cell-code}\n# 1. Best method for warp recovery\nbest_by_wt <- dt[failure == FALSE,\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(method, warp_type)\n][, .(best = method[which.min(mise)]), by = warp_type]\nbest_overall <- dt[failure == FALSE & warp_type != \"affine\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = method][which.min(mise), method]\n# Check: does it win on every DGP?\nper_dgp <- dt[failure == FALSE & warp_type != \"affine\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(dgp, method)\n][, .(best = method[which.min(mise)]), by = dgp]\nn_wins <- sum(per_dgp$best == best_overall)\nn_dgps_dp <- nrow(per_dgp)\n\n# Check if this holds on both templates\nper_tpl <- dt[failure == FALSE & warp_type != \"affine\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(method, template)\n][, .(best = method[which.min(mise)]), by = template]\nsame_on_both <- length(unique(per_tpl$best)) == 1\n\nif (same_on_both) {\n  cat(sprintf(\n    \"1. **%s is the best general-purpose method** for warp recovery on domain-preserving warps (simple + complex), ranking first on %d of %d DGPs. This holds for both harmonic and wiggly templates when pooling over noise levels. However, the method:template and method:noise interactions are substantial (@sec-method-template, @sec-method-noise) — rankings can shift in specific template/noise combinations.\\n\\n\",\n    mlabs[best_overall], n_wins, n_dgps_dp\n  ))\n} else {\n  h_best <- mlabs[per_tpl[template == \"harmonic\", best]]\n  w_best <- mlabs[per_tpl[template == \"wiggly\", best]]\n  cat(sprintf(\n    \"1. **No single best method**: %s is best on wiggly templates, but %s is best on harmonic templates (when pooling over noise). The method:template interaction (@sec-method-template) makes global 'best method' claims misleading. %s achieves the lowest *pooled* median and ranks first on %d of %d DGPs, but this reflects effect sizes within templates, not a uniform advantage.\\n\\n\",\n    w_best, h_best, mlabs[best_overall], n_wins, n_dgps_dp\n  ))\n}\n```\n\n1. **No single best method**: SRVF is best on wiggly templates, but FDA (default) is best on harmonic templates (when pooling over noise). The method:template interaction (@sec-method-template) makes global 'best method' claims misleading. SRVF achieves the lowest *pooled* median and ranks first on 8 of 12 DGPs, but this reflects effect sizes within templates, not a uniform advantage.\n\n```{.r .cell-code}\n# 2. Amplitude degradation\nbest_highrank_sum <- dt[failure == FALSE & amplitude == \"highrank\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = method][which.min(mise), method]\nbest_none_sum <- dt[failure == FALSE & amplitude == \"none\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = method][which.min(mise), method]\ncat(sprintf(\n  \"2. **Amplitude variation degrades warp recovery for most methods**, but the pattern is not universal (see @sec-q2 for per-ladder details). %s retains the lowest absolute MISE under high-rank amplitude.\\n\\n\",\n  mlabs[best_highrank_sum]\n))\n```\n\n2. **Amplitude variation degrades warp recovery for most methods**, but the pattern is not universal (see @sec-q2 for per-ladder details). SRVF retains the lowest absolute MISE under high-rank amplitude.\n\n```{.r .cell-code}\n# 3. Affine DGPs\naffine_best <- best_by_wt[warp_type == \"affine\", best]\naffine_ranks <- dt[failure == FALSE & warp_type == \"affine\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = method][order(mise)]\n# Check if affine wins uniformly across conditions\naffine_cond <- dt[failure == FALSE & warp_type == \"affine\",\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(method, severity, noise_sd)\n][, .(best = method[which.min(mise)]), by = .(severity, noise_sd)]\nn_affine_wins <- sum(affine_cond$best == \"affine_ss\")\nn_affine_conds <- nrow(affine_cond)\n\nif (affine_best == \"affine_ss\") {\n  ratio_2nd <- affine_ranks$mise[2] / affine_ranks$mise[1]\n  if (n_affine_wins == n_affine_conds) {\n    cat(sprintf(\n      \"3. **Affine (S+S) performs as expected on affine DGPs** — it achieves the lowest MISE across all %d conditions (%.1f$\\\\times$ lower than %s pooled). See @sec-affine-note.\\n\\n\",\n      n_affine_conds, ratio_2nd, mlabs[affine_ranks$method[2]]\n    ))\n  } else {\n    cat(sprintf(\n      \"3. **Affine (S+S) wins on affine DGPs overall** (%.1f$\\\\times$ lower MISE than %s pooled), but not uniformly — it ranks first in %d of %d severity/noise conditions. See @sec-affine-note.\\n\\n\",\n      ratio_2nd, mlabs[affine_ranks$method[2]], n_affine_wins, n_affine_conds\n    ))\n  }\n} else {\n  cat(sprintf(\n    \"3. **The affine method underperforms on affine DGPs** despite being well-specified — %s achieves lower MISE (see @sec-affine-note).\\n\\n\",\n    mlabs[affine_best]\n  ))\n}\n```\n\n3. **Affine (S+S) wins on affine DGPs overall** (2.4$\\times$ lower MISE than SRVF pooled), but not uniformly — it ranks first in 5 of 6 severity/noise conditions. See @sec-affine-note.\n\n```{.r .cell-code}\n# 4. Failure rates\nfail_rates <- dt[, .(rate = 100 * mean(failure)), by = method][order(-rate)]\noverall_fail <- 100 * mean(dt$failure)\nif (overall_fail < 0.1) {\n  cat(sprintf(\n    \"4. **Near-zero failure rate** (%.2f%% overall). %s has the highest rate at %.2f%%. See @sec-failures for details.\\n\\n\",\n    overall_fail, mlabs[fail_rates$method[1]], fail_rates$rate[1]\n  ))\n} else {\n  top2 <- fail_rates[1:min(2, .N)]\n  cat(sprintf(\n    \"4. **Failure rates**: %s (%.1f%%) and %s (%.1f%%) have the highest failure rates. See @sec-failures for error analysis.\\n\\n\",\n    mlabs[top2$method[1]], top2$rate[1],\n    mlabs[top2$method[min(2, nrow(top2))]], top2$rate[min(2, nrow(top2))]\n  ))\n}\n```\n\n4. **Near-zero failure rate** (0.02% overall). Landmark (auto) has the highest rate at 0.11%. See @sec-failures for details.\n\n```{.r .cell-code}\n# 5. Noise/severity sensitivity\n# Recompute here to avoid dependency on chunk-local variables\nratios_sum <- degradation_ratios(dt)\nnoise_sum <- ratios_sum$noise[\n  severity == \"0.5\" & is.finite(noise_ratio),\n  .(ratio = median(noise_ratio, na.rm = TRUE)),\n  by = .(method, noise_sd)\n][order(noise_sd, -ratio)]\nsev_sum <- ratios_sum$severity[\n  noise_sd == \"0\" & is.finite(severity_ratio),\n  .(ratio = median(severity_ratio, na.rm = TRUE)),\n  by = method\n][order(-ratio)]\n# Use highest noise level for the summary\nhighest_noise <- max(as.numeric(as.character(noise_sum$noise_sd)))\nnoise_worst_hn <- noise_sum[noise_sd == as.character(highest_noise)][which.max(ratio)]\nnoise_best_hn <- noise_sum[noise_sd == as.character(highest_noise)][which.min(ratio)]\nsev_worst <- sev_sum[1]\nnoise_robust_txt <- if (noise_best_hn$ratio < 1) {\n  sprintf(\"%s appears most robust (%.1f$\\\\times$, but ratios $<$ 1 likely reflect regularization artifacts, not genuine improvement from noise)\",\n    mlabs[noise_best_hn$method], noise_best_hn$ratio)\n} else {\n  sprintf(\"%s is most robust (%.1f$\\\\times$)\", mlabs[noise_best_hn$method], noise_best_hn$ratio)\n}\ncat(sprintf(\n  \"5. **Noise sensitivity varies sharply**: at noise=%.1f, %s is most noise-sensitive (%.1f$\\\\times$ degradation ratio) and %s. At noise=0, severity hits %s hardest (%.1f$\\\\times$ degradation from sev=0.5 to 1.0). See @sec-sensitivity.\\n\\n\",\n  highest_noise,\n  mlabs[noise_worst_hn$method], noise_worst_hn$ratio,\n  noise_robust_txt,\n  mlabs[sev_worst$method], sev_worst$ratio\n))\n```\n\n5. **Noise sensitivity varies sharply**: at noise=0.3, SRVF is most noise-sensitive (97.4$\\times$ degradation ratio) and FDA (crit 1) appears most robust (0.9$\\times$, but ratios $<$ 1 likely reflect regularization artifacts, not genuine improvement from noise). At noise=0, severity hits SRVF hardest (9.8$\\times$ degradation from sev=0.5 to 1.0). See @sec-sensitivity.\n\n```{.r .cell-code}\n# 6. Landmark\nlm_rank <- dt[failure == FALSE,\n  .(mise = median(warp_mise, na.rm = TRUE)),\n  by = .(dgp, method)\n][, rank := rank(mise), by = dgp\n][method == \"landmark_auto\", .(mean_rank = mean(rank))]\nlm_fail <- fail_rates[method == \"landmark_auto\", rate]\ncat(sprintf(\n  \"6. **Landmark (auto) is competitive** (mean rank %.1f across DGPs) with near-zero failure rate (%.1f%%) and fast runtime. Its weakness is under-registration (registration ratio well below 1) and variability when landmark detection is unreliable.\\n\\n\",\n  lm_rank$mean_rank, lm_fail\n))\n```\n\n6. **Landmark (auto) is competitive** (mean rank 2.9 across DGPs) with near-zero failure rate (0.1%) and fast runtime. Its weakness is under-registration (registration ratio well below 1) and variability when landmark detection is unreliable.\n\n```{.r .cell-code}\n# 7. AVR\navr_summary <- dt[amplitude != \"none\" & failure == FALSE & !is.na(amp_variance_ratio),\n  .(avr = median(amp_variance_ratio, na.rm = TRUE)), by = method]\noverreg_methods <- avr_summary[avr < 0.9, method]\ncat(\"7. **Phase-amplitude separation varies by method**: \")\n```\n\n7. **Phase-amplitude separation varies by method**: \n\n```{.r .cell-code}\nif (length(overreg_methods) > 0) {\n  cat(sprintf(\n    \"%s show median AVR < 1, suggesting over-registration that absorbs amplitude into phase. \",\n    paste(mlabs[overreg_methods], collapse = \" and \")\n  ))\n}\nunderreg_methods <- avr_summary[avr > 1.1, method]\nif (length(underreg_methods) > 0) {\n  cat(sprintf(\n    \"%s show AVR > 1 (under-registration or template bias inflating residuals). \",\n    paste(mlabs[underreg_methods], collapse = \" and \")\n  ))\n}\n```\n\nAffine (S+S) and FDA (crit 1) and FDA (default) and Landmark (auto) and SRVF show AVR > 1 (under-registration or template bias inflating residuals). \n\n```{.r .cell-code}\nnear_one <- avr_summary[avr >= 0.9 & avr <= 1.1, method]\nif (length(near_one) > 0) {\n  cat(sprintf(\n    \"%s show near-calibrated AVR. \",\n    paste(mlabs[near_one], collapse = \" and \")\n  ))\n}\ncat(\"Note that AVR > 1 can reflect either residual phase variation or template estimation error — these effects are confounded.\\n\\n\")\n```\n\nNote that AVR > 1 can reflect either residual phase variation or template estimation error — these effects are confounded.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwarp_med <- dt[failure == FALSE,\n  .(warp_mise = round(median(warp_mise, na.rm = TRUE), 4)),\n  by = method]\ntpl_med <- dt[failure == FALSE,\n  .(template_mise = round(median(template_mise, na.rm = TRUE), 4)),\n  by = method]\nrr_med <- dt[\n  failure == FALSE & !is.na(registration_ratio_median),\n  .(reg_ratio = round(median(registration_ratio_median, na.rm = TRUE), 2)),\n  by = method\n]\nruntime <- dt[failure == FALSE,\n  .(time_s = round(median(time_per_curve, na.rm = TRUE), 3)),\n  by = method]\nfail_rate <- dt[, .(fail_pct = round(100 * mean(failure), 2)), by = method]\n\nsummary_parts <- list(warp_med, tpl_med, rr_med, runtime, fail_rate)\n\n# Add elastic distance if available\nif (\"template_elastic_dist\" %in% names(dt)) {\n  elastic_med <- dt[failure == FALSE & !is.na(template_elastic_dist),\n    .(elastic_dist = round(median(template_elastic_dist, na.rm = TRUE), 4)),\n    by = method]\n  summary_parts <- c(summary_parts[1:2], list(elastic_med), summary_parts[3:5])\n}\n\nsummary_dt <- Reduce(function(a, b) merge(a, b, by = \"method\"), summary_parts)\n\ncol_names <- c(\"Method\", \"Warp MISE\", \"Template MISE\")\nif (\"template_elastic_dist\" %in% names(dt)) col_names <- c(col_names, \"Elastic dist.\")\ncol_names <- c(col_names, \"Reg. ratio\", \"Time/curve (s)\", \"Failure %\")\n\nknitr::kable(\n  summary_dt[order(method)],\n  col.names = col_names,\n  caption = \"Summary per method (medians pooled across all conditions). Pooled medians hide strong method × template and method × noise interactions — see conditional analyses above. Reg. ratio: 1 = perfectly calibrated. Time/curve: median seconds.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary per method (medians pooled across all conditions). Pooled medians hide strong method × template and method × noise interactions — see conditional analyses above. Reg. ratio: 1 = perfectly calibrated. Time/curve: median seconds.\n\n|Method        | Warp MISE| Template MISE| Elastic dist.| Reg. ratio| Time/curve (s)| Failure %|\n|:-------------|---------:|-------------:|-------------:|----------:|--------------:|---------:|\n|srvf          |     0.001|         0.052|         0.764|       0.95|          0.180|      0.00|\n|fda_default   |     0.005|         0.084|         1.015|       1.20|          0.118|      0.00|\n|fda_crit1     |     0.005|         0.084|         0.944|       1.25|          0.200|      0.00|\n|affine_ss     |     0.046|         0.080|         1.048|       1.04|          0.094|      0.00|\n|landmark_auto |     0.008|         0.075|         0.880|       0.37|          0.003|      0.11|\n\n\n:::\n:::\n\n\n# Session Info {.unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31)\nPlatform: x86_64-pc-linux-gnu\nRunning under: Linux Mint 22.1\n\nMatrix products: default\nBLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.12.0 \nLAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.12.0  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Europe/Berlin\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] tf_0.4.0          car_3.1-3         carData_3.0-5     patchwork_1.3.2  \n[5] data.table_1.17.8 ggplot2_4.0.2    \n\nloaded via a namespace (and not attached):\n [1] generics_0.1.4     lattice_0.22-7     pracma_2.4.6       digest_0.6.39     \n [5] magrittr_2.0.4     evaluate_1.0.5     grid_4.5.2         RColorBrewer_1.1-3\n [9] mvtnorm_1.3-6      fastmap_1.2.0      rprojroot_2.1.1    jsonlite_2.0.0    \n[13] Matrix_1.7-4       backports_1.5.0    Formula_1.2-5      mgcv_1.9-4        \n[17] purrr_1.2.1        scales_1.4.0.9000  codetools_0.2-20   abind_1.4-8       \n[21] cli_3.6.5          rlang_1.1.7        splines_4.5.2      withr_3.0.2       \n[25] yaml_2.3.12        otel_0.2.0         tools_4.5.2        checkmate_2.3.4   \n[29] dplyr_1.2.0        here_1.0.2         vctrs_0.7.1        R6_2.6.1          \n[33] zoo_1.8-15         lifecycle_1.0.5    htmlwidgets_1.6.4  pkgconfig_2.0.3   \n[37] pillar_1.11.1      gtable_0.3.6       glue_1.8.0         xfun_0.56         \n[41] tibble_3.3.1       tidyselect_1.2.1   knitr_1.51         farver_2.1.2      \n[45] htmltools_0.5.8.1  nlme_3.1-168       labeling_0.4.3     rmarkdown_2.30    \n[49] compiler_4.5.2     S7_0.2.1          \n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}